In [1]:
pip install imbalanced-learn

     |████████████████████████████████| 167 kB 3.5 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [37]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_41ba5eff349d49bd981e321191d9d62c.csv"
df1=pd.read_csv(url,header=None,na_values=["?"])
df1.head()

0         1  2       3       4     5  6    7  8  9   ... 61 62      63 64  \
0  f      mild  f  normal  normal   NaN  t  NaN  f  f  ...  f  f  normal  t   
1  f  moderate  f  normal  normal   NaN  t  NaN  f  f  ...  f  f  normal  t   
2  t      mild  t     NaN  absent  mild  t  NaN  f  f  ...  f  f  normal  t   
3  t      mild  t     NaN  absent  mild  f  NaN  f  f  ...  f  f  normal  t   
4  t      mild  f  normal  normal  mild  t  NaN  f  f  ...  f  f    good  t   

   65 66 67 68  69                               70  
0   a  f  f  f  p1                 cochlear_unknown  
1   a  f  f  f  p2                 cochlear_unknown  
2  as  f  f  f  p3      mixed_cochlear_age_fixation  
3   b  f  f  f  p4  mixed_cochlear_age_otitis_media  
4   a  f  f  f  p5                     cochlear_age  

[5 rows x 71 columns]

In [38]:
df1.shape

(200, 71)

In [39]:
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_60101f663d2d47bdb54aceba93218cd0.csv"
df2=pd.read_csv(url,header=None,na_values=["?"])
df2.head()

0       1  2       3       4           5  6   7  8  9   ... 61 62  \
0  t    mild  f  normal  normal  unmeasured  f NaN  f  f  ...  f  f   
1  t    mild  f  normal  normal  unmeasured  f NaN  f  f  ...  f  f   
2  t  normal  f  normal  normal  unmeasured  f NaN  f  f  ...  f  f   
3  t    mild  f  normal  normal  unmeasured  f NaN  f  f  ...  f  f   
4  t    mild  f  normal  normal  unmeasured  f NaN  f  f  ...  f  f   

           63 64 65 66 67 68  69                      70  
0        good  t  a  f  f  f  t1            cochlear_age  
1        good  t  a  f  f  f  t2            cochlear_age  
2        good  t  a  f  f  f  t3  cochlear_age_and_noise  
3  unmeasured  t  a  f  f  f  t4  cochlear_age_and_noise  
4      normal  t  a  f  f  f  t5            cochlear_age  

[5 rows x 71 columns]

In [40]:
df2.shape

(26, 71)

In [41]:
df=pd.concat([df1,df2],axis=0)
df.shape

(226, 71)

In [42]:
y=pd.DataFrame(df.iloc[:,70]).rename(columns={70:"Class"})
counts=pd.DataFrame(y.groupby("Class")["Class"].count())
counts

Class
Class                                  
acoustic_neuroma                      1
bells_palsy                           1
cochlear_age                         57
cochlear_age_and_noise               22
cochlear_age_plus_poss_menieres       1
cochlear_noise_and_heredity           2
cochlear_poss_noise                  20
cochlear_unknown                     48
conductive_discontinuity              2
conductive_fixation                   6
mixed_cochlear_age_fixation           2
mixed_cochlear_age_otitis_media       4
mixed_cochlear_age_s_om               2
mixed_cochlear_unk_discontinuity      2
mixed_cochlear_unk_fixation           9
mixed_cochlear_unk_ser_om             3
mixed_poss_central_om                 1
mixed_poss_noise_om                   2
normal_ear                           22
otitis_media                          4
poss_central                          1
possible_brainstem_disorder           4
possible_menieres                     8
retrocochlear_unknown                 2

In [43]:
import numpy as np
len(np.unique(y))

24

In [44]:
classes=counts[counts["Class"]>=3]
classes

Class
Class                                 
cochlear_age                        57
cochlear_age_and_noise              22
cochlear_poss_noise                 20
cochlear_unknown                    48
conductive_fixation                  6
mixed_cochlear_age_otitis_media      4
mixed_cochlear_unk_fixation          9
mixed_cochlear_unk_ser_om            3
normal_ear                          22
otitis_media                         4
possible_brainstem_disorder          4
possible_menieres                    8

In [45]:
sub_df=df.drop(columns=70)
sub_df.head()

0         1  2       3       4     5  6    7  8  9   ... 60 61 62      63  \
0  f      mild  f  normal  normal   NaN  t  NaN  f  f  ...  f  f  f  normal   
1  f  moderate  f  normal  normal   NaN  t  NaN  f  f  ...  f  f  f  normal   
2  t      mild  t     NaN  absent  mild  t  NaN  f  f  ...  f  f  f  normal   
3  t      mild  t     NaN  absent  mild  f  NaN  f  f  ...  f  f  f  normal   
4  t      mild  f  normal  normal  mild  t  NaN  f  f  ...  f  f  f    good   

  64  65 66 67 68  69  
0  t   a  f  f  f  p1  
1  t   a  f  f  f  p2  
2  t  as  f  f  f  p3  
3  t   b  f  f  f  p4  
4  t   a  f  f  f  p5  

[5 rows x 70 columns]

In [46]:
df=pd.concat([sub_df,y],axis=1)
df.head()

0         1  2       3       4     5  6    7  8  9  ... 61 62      63 64  \
0  f      mild  f  normal  normal   NaN  t  NaN  f  f  ...  f  f  normal  t   
1  f  moderate  f  normal  normal   NaN  t  NaN  f  f  ...  f  f  normal  t   
2  t      mild  t     NaN  absent  mild  t  NaN  f  f  ...  f  f  normal  t   
3  t      mild  t     NaN  absent  mild  f  NaN  f  f  ...  f  f  normal  t   
4  t      mild  f  normal  normal  mild  t  NaN  f  f  ...  f  f    good  t   

   65 66 67 68  69                            Class  
0   a  f  f  f  p1                 cochlear_unknown  
1   a  f  f  f  p2                 cochlear_unknown  
2  as  f  f  f  p3      mixed_cochlear_age_fixation  
3   b  f  f  f  p4  mixed_cochlear_age_otitis_media  
4   a  f  f  f  p5                     cochlear_age  

[5 rows x 71 columns]

In [47]:
classes.index.tolist()

['cochlear_age',
 'cochlear_age_and_noise',
 'cochlear_poss_noise',
 'cochlear_unknown',
 'conductive_fixation',
 'mixed_cochlear_age_otitis_media',
 'mixed_cochlear_unk_fixation',
 'mixed_cochlear_unk_ser_om',
 'normal_ear',
 'otitis_media',
 'possible_brainstem_disorder',
 'possible_menieres']

In [48]:
len(classes.index.tolist())

12

In [51]:
df1=df[df["Class"]=='cochlear_age']
df2=df[df["Class"]=='cochlear_age_and_noise']
df3=df[df["Class"]=='cochlear_poss_noise']
df4=df[df["Class"]=='cochlear_unknown']
df5=df[df["Class"]=='conductive_fixation']
df6=df[df["Class"]=='mixed_cochlear_age_otitis_media']
df7=df[df["Class"]=='mixed_cochlear_unk_fixation']
df8=df[df["Class"]=='mixed_cochlear_unk_ser_om']
df9=df[df["Class"]=='normal_ear']
df10=df[df["Class"]=='otitis_media']
df11=df[df["Class"]=='possible_brainstem_disorder']
df12=df[df["Class"]=='possible_menieres']

df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12],axis=0)
df.shape

(207, 71)

In [52]:
missing=pd.DataFrame(df.isna().any()).rename(columns={0:"Missing"})
missing=missing[missing["Missing"]==True]
missing

Missing
3      True
4      True
5      True
7      True
58     True
59     True
63     True

In [53]:
missing_values=df.iloc[:,missing.index.tolist()]
missing_values

3         4           5    7       58        59         63
4      normal    normal        mild  NaN  normal    normal       good
5      normal    normal        mild  NaN  normal    normal  very_good
9    elevated    absent        mild  NaN  normal    absent       good
10     normal    absent        mild  NaN  normal    absent  very_good
11     normal    normal         NaN  NaN  normal    normal       good
..        ...       ...         ...  ...     ...       ...        ...
96     normal    normal    moderate  NaN  normal    normal  very_poor
97   elevated    normal  unmeasured  NaN  normal    normal  very_poor
113    absent    absent        mild  NaN  absent  elevated  very_good
149    normal    normal         NaN  NaN  normal    normal     normal
185    absent  elevated        mild  NaN  absent    absent     normal

[207 rows x 7 columns]

In [54]:
missing_percentage=pd.DataFrame(missing_values.isna().sum()/len(missing_values)).rename(columns={0:"Percentage"})
missing_percentage

Percentage
3     0.014493
4     0.014493
5     0.347826
7     0.990338
58    0.019324
59    0.009662
63    0.028986

In [55]:
large_missing=missing_percentage[missing_percentage["Percentage"]>0.15]
large_missing

Percentage
5    0.347826
7    0.990338

In [56]:
missing_values=missing_values.drop(columns=large_missing.index)
missing_values

3         4       58        59         63
4      normal    normal  normal    normal       good
5      normal    normal  normal    normal  very_good
9    elevated    absent  normal    absent       good
10     normal    absent  normal    absent  very_good
11     normal    normal  normal    normal       good
..        ...       ...     ...       ...        ...
96     normal    normal  normal    normal  very_poor
97   elevated    normal  normal    normal  very_poor
113    absent    absent  absent  elevated  very_good
149    normal    normal  normal    normal     normal
185    absent  elevated  absent    absent     normal

[207 rows x 5 columns]

In [57]:
missing_values.mode()

3       4       58      59      63
0  normal  normal  normal  normal  normal

In [58]:
missing_values=missing_values.fillna("normal")
missing_values.isna().any()

3     False
4     False
58    False
59    False
63    False
dtype: bool

In [59]:
indices=missing_values.columns.tolist()+large_missing.index.tolist()

In [60]:
sub_df=df.drop(columns=indices)
sub_df.head()

0     1  2  6  8  9 10 11 12 13  ... 60 61 62 64 65 66 67 68   69  \
4   t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  t  a  f  f  f   p5   
5   t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  t  a  f  f  f   p6   
9   t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  t  a  f  f  f  p10   
10  t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  t  a  f  f  f  p11   
11  t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  t  a  f  f  f  p12   

           Class  
4   cochlear_age  
5   cochlear_age  
9   cochlear_age  
10  cochlear_age  
11  cochlear_age  

[5 rows x 64 columns]

In [61]:
sub_df=sub_df.drop(columns=69)
sub_df.head()

0     1  2  6  8  9 10 11 12 13  ... 57 60 61 62 64 65 66 67 68  \
4   t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  f  t  a  f  f  f   
5   t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  f  t  a  f  f  f   
9   t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  f  t  a  f  f  f   
10  t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  f  t  a  f  f  f   
11  t  mild  f  t  f  f  f  f  f  f  ...  f  f  f  f  t  a  f  f  f   

           Class  
4   cochlear_age  
5   cochlear_age  
9   cochlear_age  
10  cochlear_age  
11  cochlear_age  

[5 rows x 63 columns]

In [62]:
df=pd.concat([missing_values,sub_df],axis=1)
df.head()

3       4      58      59         63  0     1  2  6  8  ... 57 60  \
4     normal  normal  normal  normal       good  t  mild  f  t  f  ...  f  f   
5     normal  normal  normal  normal  very_good  t  mild  f  t  f  ...  f  f   
9   elevated  absent  normal  absent       good  t  mild  f  t  f  ...  f  f   
10    normal  absent  normal  absent  very_good  t  mild  f  t  f  ...  f  f   
11    normal  normal  normal  normal       good  t  mild  f  t  f  ...  f  f   

   61 62 64 65 66 67 68         Class  
4   f  f  t  a  f  f  f  cochlear_age  
5   f  f  t  a  f  f  f  cochlear_age  
9   f  f  t  a  f  f  f  cochlear_age  
10  f  f  t  a  f  f  f  cochlear_age  
11  f  f  t  a  f  f  f  cochlear_age  

[5 rows x 68 columns]

In [63]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df=df.apply(le.fit_transform)
df.head()

3  4  58  59  63  0  1  2  6  8  ...  57  60  61  62  64  65  66  67  68  \
4   2  2   2   2   0  1  0  0  1  0  ...   0   0   0   0   1   0   0   0   0   
5   2  2   2   2   4  1  0  0  1  0  ...   0   0   0   0   1   0   0   0   0   
9   1  0   2   0   0  1  0  0  1  0  ...   0   0   0   0   1   0   0   0   0   
10  2  0   2   0   4  1  0  0  1  0  ...   0   0   0   0   1   0   0   0   0   
11  2  2   2   2   0  1  0  0  1  0  ...   0   0   0   0   1   0   0   0   0   

    Class  
4       0  
5       0  
9       0  
10      0  
11      0  

[5 rows x 68 columns]

In [64]:
X=df.drop(["Class"],axis=1)
X.head()

3   4   58  59  63  0   1   2   6   8   ...  56  57  60  61  62  64  65  \
4    2   2   2   2   0   1   0   0   1   0  ...   0   0   0   0   0   1   0   
5    2   2   2   2   4   1   0   0   1   0  ...   0   0   0   0   0   1   0   
9    1   0   2   0   0   1   0   0   1   0  ...   0   0   0   0   0   1   0   
10   2   0   2   0   4   1   0   0   1   0  ...   0   0   0   0   0   1   0   
11   2   2   2   2   0   1   0   0   1   0  ...   0   0   0   0   0   1   0   

    66  67  68  
4    0   0   0  
5    0   0   0  
9    0   0   0  
10   0   0   0  
11   0   0   0  

[5 rows x 67 columns]

In [65]:
y=df[["Class"]]
y.head()

Class
4       0
5       0
9       0
10      0
11      0

In [66]:
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif

# feature extraction. We are going to output the selection scores for all features and select the features with the highest scores.
test = SelectKBest(score_func=mutual_info_classif, k="all")
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
# summarize scores
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

scores
5   0.584540
63  0.513853
62  0.401193
7   0.390066
15  0.377589
..       ...
44  0.000000
35  0.000000
42  0.000000
41  0.000000
33  0.000000

[67 rows x 1 columns]

In [67]:
X_scores=scores[scores["scores"]>0]
len(X_scores)

46

In [68]:
X=X.iloc[:,X_scores.index]
X.head()

0   65  64  2   14  1   58  4   3   57  ...  26  68  38  49  24  12  27  \
4    1   0   1   0   0   0   2   2   2   0  ...   0   0   0   0   0   0   0   
5    1   0   1   0   0   0   2   2   2   0  ...   0   0   0   0   0   0   0   
9    1   0   1   0   0   0   2   0   1   0  ...   0   0   0   0   0   0   0   
10   1   0   1   0   0   0   2   0   2   0  ...   0   0   0   0   0   0   0   
11   1   0   1   0   0   0   2   2   2   0  ...   0   0   0   0   0   0   0   

    23  39  47  
4    0   0   0  
5    0   0   0  
9    0   0   0  
10   0   0   0  
11   0   0   0  

[5 rows x 46 columns]

In [69]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X))
X.head()

0         1         2         3         4        5         6   \
0  1.17444 -0.336479  0.248069 -0.336011 -0.601533 -0.89588  0.671542   
1  1.17444 -0.336479  0.248069 -0.336011 -0.601533 -0.89588  0.671542   
2  1.17444 -0.336479  0.248069 -0.336011 -0.601533 -0.89588  0.671542   
3  1.17444 -0.336479  0.248069 -0.336011 -0.601533 -0.89588  0.671542   
4  1.17444 -0.336479  0.248069 -0.336011 -0.601533 -0.89588  0.671542   

         7         8        9   ...        36        37        38        39  \
0  0.661438  0.718916 -0.26933  ... -0.172774 -0.098773 -0.140372 -0.069673   
1  0.661438  0.718916 -0.26933  ... -0.172774 -0.098773 -0.140372 -0.069673   
2 -1.946517 -0.481210 -0.26933  ... -0.172774 -0.098773 -0.140372 -0.069673   
3 -1.946517  0.718916 -0.26933  ... -0.172774 -0.098773 -0.140372 -0.069673   
4  0.661438  0.718916 -0.26933  ... -0.172774 -0.098773 -0.140372 -0.069673   

         40   41        42        43        44        45  
0 -0.213201  0.0 -0.069673 -0.098773 -0.236902 -0.069673  
1 -0.213201  0.0 -0.069673 -0.098773 -0.236902 -0.069673  
2 -0.213201  0.0 -0.069673 -0.098773 -0.236902 -0.069673  
3 -0.213201  0.0 -0.069673 -0.098773 -0.236902 -0.069673  
4 -0.213201  0.0 -0.069673 -0.098773 -0.236902 -0.069673  

[5 rows x 46 columns]

In [70]:
from imblearn.ensemble import BalancedRandomForestClassifier
import numpy as np
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [80]:
BForest=BalancedRandomForestClassifier(n_estimators=325,criterion="gini",max_depth=7,min_samples_split=3,
                                       min_samples_leaf=1,max_features="log2",bootstrap=False,
                                       sampling_strategy="auto",replacement=False,n_jobs=-1,warm_start=False,
                                       random_state=0)
scores=cross_val_score(BForest,X,np.asarray(y).reshape(y.shape[0],),cv=10)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)


Accuracy:  0.8502380952380951 +/- 0.07011045706937155


In [81]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(BForest, X, np.asarray(y).reshape(y.shape[0],), cv=10)
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)


Confusion matrix: 
 [[53  2  0  0  0  2  0  0  0  0  0  0]
 [ 0 22  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 18  1  0  0  0  0  1  0  0  0]
 [ 0  0  3 34  0  0  0  1  5  0  5  0]
 [ 0  0  0  0  6  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  4  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0  0]
 [ 0  0  1  0  0  0  0  0 20  0  1  0]
 [ 0  0  0  0  1  0  1  1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  7]]
