In [1]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_3f9d4f14b59f43afae1ba4656ba2b2e2.csv"
df=pd.read_csv(url)
df.head()

behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0                   10               13                       12   
1                   10               11                       11   
2                   10               15                        3   
3                   10               11                       10   
4                    8               11                        7   

   intention_aggregation  intention_commitment  attitude_consistency  \
0                      4                     7                     9   
1                     10                    14                     7   
2                      2                    14                     8   
3                     10                    15                     7   
4                      8                    10                     7   

   attitude_spontaneity  norm_significantPerson  norm_fulfillment  \
0                    10                       1                 8   
1                     7                       5                 5   
2                    10                       1                 4   
3                     7                       1                 5   
4                     8                       1                 5   

   perception_vulnerability  perception_severity  motivation_strength  \
0                         7                    3                   14   
1                         4                    2                   15   
2                         7                    2                    7   
3                         4                    2                   15   
4                         3                    2                   15   

   motivation_willingness  socialSupport_emotionality  \
0                       8                           5   
1                      13                           7   
2                       3                           3   
3                      13                           7   
4                       5                           3   

   socialSupport_appreciation  socialSupport_instrumental  \
0                           7                          12   
1                           6                           5   
2                           6                          11   
3                           4                           4   
4                           6                          12   

   empowerment_knowledge  empowerment_abilities  empowerment_desires  \
0                     12                     11                    8   
1                      5                      4                    4   
2                      3                      3                   15   
3                      4                      4                    4   
4                      5                      4                    7   

   ca_cervix  
0          1  
1          1  
2          1  
3          1  
4          1

In [2]:
df.shape

(72, 20)

In [3]:
df.isna().any()

behavior_sexualRisk           False
behavior_eating               False
behavior_personalHygine       False
intention_aggregation         False
intention_commitment          False
attitude_consistency          False
attitude_spontaneity          False
norm_significantPerson        False
norm_fulfillment              False
perception_vulnerability      False
perception_severity           False
motivation_strength           False
motivation_willingness        False
socialSupport_emotionality    False
socialSupport_appreciation    False
socialSupport_instrumental    False
empowerment_knowledge         False
empowerment_abilities         False
empowerment_desires           False
ca_cervix                     False
dtype: bool

In [4]:
df.groupby("ca_cervix").count().T.head()

ca_cervix                 0   1
behavior_sexualRisk      51  21
behavior_eating          51  21
behavior_personalHygine  51  21
intention_aggregation    51  21
intention_commitment     51  21

In [5]:
X=df.drop(["ca_cervix"],axis=1)
X.head()

behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0                   10               13                       12   
1                   10               11                       11   
2                   10               15                        3   
3                   10               11                       10   
4                    8               11                        7   

   intention_aggregation  intention_commitment  attitude_consistency  \
0                      4                     7                     9   
1                     10                    14                     7   
2                      2                    14                     8   
3                     10                    15                     7   
4                      8                    10                     7   

   attitude_spontaneity  norm_significantPerson  norm_fulfillment  \
0                    10                       1                 8   
1                     7                       5                 5   
2                    10                       1                 4   
3                     7                       1                 5   
4                     8                       1                 5   

   perception_vulnerability  perception_severity  motivation_strength  \
0                         7                    3                   14   
1                         4                    2                   15   
2                         7                    2                    7   
3                         4                    2                   15   
4                         3                    2                   15   

   motivation_willingness  socialSupport_emotionality  \
0                       8                           5   
1                      13                           7   
2                       3                           3   
3                      13                           7   
4                       5                           3   

   socialSupport_appreciation  socialSupport_instrumental  \
0                           7                          12   
1                           6                           5   
2                           6                          11   
3                           4                           4   
4                           6                          12   

   empowerment_knowledge  empowerment_abilities  empowerment_desires  
0                     12                     11                    8  
1                      5                      4                    4  
2                      3                      3                   15  
3                      4                      4                    4  
4                      5                      4                    7

In [6]:
y=df[["ca_cervix"]]
y.head()

ca_cervix
0          1
1          1
2          1
3          1
4          1

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)
X.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0             0.282843         0.088848                 0.304267   
1             0.282843        -0.764090                -0.027661   
2             0.282843         0.941785                -2.683082   
3             0.282843        -0.764090                -0.359588   
4            -1.414214        -0.764090                -1.355371   

   intention_aggregation  intention_commitment  attitude_consistency  \
0              -1.435337             -2.691824              1.203152   
1               0.771302              0.276840             -0.119397   
2              -2.170883              0.276840              0.541878   
3               0.771302              0.700934             -0.119397   
4               0.035756             -1.419539             -0.119397   

   attitude_spontaneity  norm_significantPerson  norm_fulfillment  \
0              0.922767               -1.159390         -0.099748   
1             -1.070410                1.022992         -0.715338   
2              0.922767               -1.159390         -0.920534   
3             -1.070410               -1.159390         -0.715338   
4             -0.406017               -1.159390         -0.715338   

   perception_vulnerability  perception_severity  motivation_strength  \
0                 -0.356554            -0.707394             0.423008   
1                 -1.063120            -1.003512             0.736994   
2                 -0.356554            -1.003512            -1.774891   
3                 -1.063120            -1.003512             0.736994   
4                 -1.298641            -1.003512             0.736994   

   motivation_willingness  socialSupport_emotionality  \
0               -0.413116                   -0.735053   
1                0.805914                   -0.260400   
2               -1.632146                   -1.209707   
3                0.805914                   -0.260400   
4               -1.144534                   -1.209707   

   socialSupport_appreciation  socialSupport_instrumental  \
0                    0.289642                    0.379106   
1                   -0.057928                   -1.253965   
2                   -0.057928                    0.145810   
3                   -0.753070                   -1.487260   
4                   -0.057928                    0.379106   

   empowerment_knowledge  empowerment_abilities  empowerment_desires  
0               0.336305               0.404687            -0.511741  
1              -1.277960              -1.280951            -1.410408  
2              -1.739179              -1.521756             1.060926  
3              -1.508570              -1.280951            -1.410408  
4              -1.277960              -1.280951            -0.736408

In [14]:
import numpy as np
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

forest=RandomForestClassifier(n_estimators=230,criterion="gini",max_depth=5,min_samples_split=4,min_samples_leaf=3,max_features="log2",bootstrap=False,n_jobs=-1,warm_start=True,class_weight="balanced_subsample",random_state=0)
scores=cross_val_score(forest,X,np.asarray(y).reshape(72,),cv=9)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/forest.py:502: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn('class_weight presets "balanced" or "balanced_subsample" are '
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/forest.py:502: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight("balanced", classes, y). In place of y you can use a large enough sample of the full traini

In [15]:
print("Accuracy: ",scores.mean())

Accuracy:  0.9208553791887125


In [16]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(forest, X, y, cv=9)
AUC = roc_auc_score(y, y_pred)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:850: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/forest.py:502: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn('class_weight presets "balanced" or "balanced_subsample" are '
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/model_selection/_val

In [17]:
print("AUC for the Random Forest model: ",AUC)

AUC for the Random Forest model:  0.8991596638655462


In [18]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[48  3]
 [ 3 18]]


In [19]:
(48+18)/72

0.9166666666666666

In [26]:
from sklearn.ensemble import GradientBoostingClassifier
gradient=GradientBoostingClassifier(loss="deviance",learning_rate=0.025,n_estimators=215,subsample=0.85,criterion="mse",min_samples_split=3,min_samples_leaf=2,max_depth=5,max_features="sqrt",random_state=0)
scores=cross_val_score(gradient,X,np.asarray(y).reshape(72,),cv=8)
print("Accuracy: ",scores.mean())

Accuracy:  0.9079861111111112


In [30]:
y_pred = cross_val_predict(gradient, X, np.asarray(y).reshape(72,), cv=8)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Gradient Boosting model: ",AUC)

AUC for the Gradient Boosting model:  0.861344537815126


In [31]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[49  2]
 [ 5 16]]


In [52]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
import numpy as np

svm=svm.SVC(C=0.5,kernel="linear",degree=2,gamma="scale",cache_size=200,
            decision_function_shape="ovr",probability=True,random_state=0)
scores=cross_val_score(svm,X,np.asarray(y).reshape(72,),cv=15)
print("Accuracy: ",scores.mean())

Accuracy:  0.9666666666666667


In [53]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(svm, X, np.asarray(y).reshape(72,), cv=15)
AUC = roc_auc_score(y, y_pred)
print("AUC for the SVM model: ",AUC)

AUC for the SVM model:  0.9425770308123248


In [54]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[50  1]
 [ 2 19]]


In [55]:
print("True positive rate: ",19/(19+2))
print("True negative rate: ",50/(50+1))

True positive rate:  0.9047619047619048
True negative rate:  0.9803921568627451


In [56]:
from sklearn.metrics import f1_score
print("F1 score: ",f1_score(y,y_pred))

F1 score:  0.9268292682926829


In [57]:
y_pred =pd.DataFrame((cross_val_predict(svm, X, y, cv=15,method="predict_proba"))).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


pred_0    pred_1
0  0.313096  0.686904
1  0.397230  0.602770
2  0.030546  0.969454
3  0.217941  0.782059
4  0.020555  0.979445

In [58]:
y_probs1=y_pred[["pred_1"]]

In [59]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [60]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [61]:
from sklearn.metrics import f1_score
scores=[f1_score(y, to_labels(y_probs1,t)) for t in thresholds]

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [62]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.41000000000000003, 0.9268292682926829)


In [63]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.410),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.410),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.410),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.410),0,y_pred.pred_1)

In [64]:
y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)

In [65]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  52


In [66]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  20


In [67]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(handle_unknown="ignore")
y_true=np.asarray(y).reshape(-1,1)
y_true=pd.DataFrame(enc.fit_transform(y_true).toarray())
y_true.head()

0    1
0  0.0  1.0
1  0.0  1.0
2  0.0  1.0
3  0.0  1.0
4  0.0  1.0

In [68]:
y_true=y_true.rename(columns={0:"y_0",1:"y_1"})

In [69]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 69)

In [70]:
print("Confusion matrix: \n",np.asarray([[50,1],[2,19]]))

Confusion matrix: 
 [[50  1]
 [ 2 19]]


No improvements.

In [68]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=4,weights="distance",algorithm="brute",leaf_size=30,p=1,n_jobs=-1)
scores=cross_val_score(KNN,X,np.asarray(y).reshape(72,),cv=8)
print("Accuracy: ",scores.mean())

Accuracy:  0.9329861111111111


In [86]:
y_pred = cross_val_predict(KNN, X,np.asarray(y).reshape(72,), cv=10)
AUC = roc_auc_score(y, y_pred)
print("AUC for the KNeighbor model: ",AUC)

AUC for the KNeighbor model:  0.8711484593837534


In [70]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[50  1]
 [ 5 16]]


In [74]:
from sklearn.gaussian_process import GaussianProcessClassifier
Gaussian=GaussianProcessClassifier(n_restarts_optimizer=4,max_iter_predict=150,warm_start=True,multi_class="one_vs_rest",n_jobs=-1,random_state=0)
scores=cross_val_score(Gaussian,X,np.asarray(y).reshape(72,),cv=8)
print("Accuracy: ",scores.mean())

Accuracy:  0.8923611111111112


In [84]:
y_pred = cross_val_predict(Gaussian, X, np.asarray(y).reshape(72,), cv=8)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Gaussian Process model: ",AUC)

AUC for the Gaussian Process model:  0.8375350140056023


In [85]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[49  2]
 [ 6 15]]


In [10]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
import numpy as np
NB=GaussianNB()
scores=cross_val_score(NB,X,np.asarray(y).reshape(72,),cv=12)
print("Accuracy: ",scores.mean())

Accuracy:  0.9416666666666668


In [13]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(NB, X, np.asarray(y).reshape(72,), cv=12)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Naive Bayes model: ",AUC)

AUC for the Naive Bayes model:  0.9327731092436975


In [15]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[49  2]
 [ 2 19]]


In [16]:
print("True positive rate: ",19/(19+2))
print("True negative rate: ",49/(49+2))

True positive rate:  0.9047619047619048
True negative rate:  0.9607843137254902


In [18]:
from sklearn.metrics import f1_score
print("F1 socre: ", f1_score(y,y_pred,average="macro"))

F1 socre:  0.9327731092436975


In [19]:
y_pred =pd.DataFrame((cross_val_predict(NB, X, y, cv=12,method="predict_proba"))).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


pred_0    pred_1
0  1.840636e-01  0.815936
1  1.968563e-01  0.803144
2  2.197436e-08  1.000000
3  1.194286e-02  0.988057
4  8.549195e-07  0.999999

In [20]:
y_probs1=y_pred[["pred_1"]]

In [21]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [22]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [23]:
from sklearn.metrics import f1_score
scores=[f1_score(y, to_labels(y_probs1,t)) for t in thresholds]

In [24]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.396, 0.9047619047619048)


In [25]:
len(y_probs1[y_probs1["pred_1"]>=0.396])

21

In [26]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.396),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.396),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.396),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.396),0,y_pred.pred_1)

In [27]:
#y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)

In [28]:
y_pred.head()

pred_0  pred_1
0     0.0     1.0
1     0.0     1.0
2     0.0     1.0
3     0.0     1.0
4     0.0     1.0

In [29]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  51


In [30]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  21


In [33]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 68)

In [34]:
print("Confusion matrix: \n",np.array([[49,2],[2,19]]))

Confusion matrix: 
 [[49  2]
 [ 2 19]]


No improvement.