In [31]:
pip install imbalanced-learn

     |████████████████████████████████| 167 kB 4.5 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_92f2928f5b064ceab0268c0ed0aa22c2.csv"
df=pd.read_csv(url,header=None)
df.head()

0     1     2     3    4     5     6     7   8
0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  cp
1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  cp
2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  cp
3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  cp
4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  cp

In [2]:
df.shape

(336, 9)

In [3]:
X=df.iloc[:,1:8]
X.head()

1     2     3    4     5     6     7
0  0.49  0.29  0.48  0.5  0.56  0.24  0.35
1  0.07  0.40  0.48  0.5  0.54  0.35  0.44
2  0.56  0.40  0.48  0.5  0.49  0.37  0.46
3  0.59  0.49  0.48  0.5  0.52  0.45  0.36
4  0.23  0.32  0.48  0.5  0.55  0.25  0.35

In [4]:
y=pd.DataFrame(df.iloc[:,8]).rename(columns={8:"Class"})
y.head()

Class
0    cp
1    cp
2    cp
3    cp
4    cp

In [5]:
y.groupby("Class")["Class"].count()

Class
cp     143
im      77
imL      2
imS      2
imU     35
om      20
omL      5
pp      52
Name: Class, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
print(X_train.shape)
print(X_test.shape)

(235, 7)
(101, 7)


In [7]:
import numpy as np
from sklearn import svm
model5=svm.SVC(random_state=0).fit(X_train,np.asarray(y_train).reshape(y_train.shape[0],))
model5

SVC(random_state=0)

In [8]:
from sklearn.metrics import accuracy_score
train_pred=model5.predict(X_train)
test_pred=model5.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,train_pred))
print("Accuracy on test data: ",accuracy_score(y_test,test_pred))

Accuracy on train data:  0.8808510638297873
Accuracy on test data:  0.900990099009901


In [9]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix for test data: \n",confusion_matrix(y_test,test_pred))

Confusion matrix for test data: 
 [[45  0  0  0  0  0  1]
 [ 2 16  0  2  0  0  0]
 [ 0  0  0  0  0  0  1]
 [ 0  2  0  9  0  0  0]
 [ 0  0  0  0  7  0  0]
 [ 0  0  0  0  0  1  0]
 [ 1  1  0  0  0  0 13]]


In [10]:
y_test.groupby("Class")["Class"].count()

Class
cp     46
im     20
imS     1
imU    11
om      7
omL     1
pp     15
Name: Class, dtype: int64

In [11]:
from sklearn.neighbors import KNeighborsClassifier
model6=KNeighborsClassifier(n_neighbors=7,weights="distance",
                           ).fit(X_train,np.asarray(y_train).reshape(y_train.shape[0],))
model6

KNeighborsClassifier(n_neighbors=7, weights='distance')

In [12]:
train_pred=model6.predict(X_train)
test_pred=model6.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,train_pred))
print("Accuracy on test data: ",accuracy_score(y_test,test_pred))

Accuracy on train data:  1.0
Accuracy on test data:  0.900990099009901


In [13]:
print("Confusion matrix for test data: \n",confusion_matrix(y_test,test_pred))

Confusion matrix for test data: 
 [[46  0  0  0  0  0  0]
 [ 2 17  0  1  0  0  0]
 [ 0  0  0  0  0  0  1]
 [ 0  3  0  8  0  0  0]
 [ 0  0  0  0  6  0  1]
 [ 0  0  0  0  0  1  0]
 [ 1  1  0  0  0  0 13]]
