In [1]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_da66db362611452c986019d15531a283.csv"
df=pd.read_csv(url)
df.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [2]:
df.shape

(299, 13)

In [3]:
df.isna().any()

age                         False
anaemia                     False
creatinine_phosphokinase    False
diabetes                    False
ejection_fraction           False
high_blood_pressure         False
platelets                   False
serum_creatinine            False
serum_sodium                False
sex                         False
smoking                     False
time                        False
DEATH_EVENT                 False
dtype: bool

In [4]:
df.groupby("DEATH_EVENT").count().T

DEATH_EVENT                 0   1
age                       203  96
anaemia                   203  96
creatinine_phosphokinase  203  96
diabetes                  203  96
ejection_fraction         203  96
high_blood_pressure       203  96
platelets                 203  96
serum_creatinine          203  96
serum_sodium              203  96
sex                       203  96
smoking                   203  96
time                      203  96

In [5]:
X=df.drop(["DEATH_EVENT"],axis=1)
X.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  
0        0     4  
1        0     6  
2        1     7  
3        0     7  
4        0     8

In [6]:
y=df[["DEATH_EVENT"]]
y.head()

DEATH_EVENT
0            1
1            1
2            1
3            1
4            1

In [7]:
import numpy as  np
np.unique(y)

array([0, 1])

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)
X.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


age   anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  1.192945 -0.871105                  0.000166 -0.847579          -1.530560   
1 -0.491279 -0.871105                  7.514640 -0.847579          -0.007077   
2  0.350833 -0.871105                 -0.449939 -0.847579          -1.530560   
3 -0.912335  1.147968                 -0.486071 -0.847579          -1.530560   
4  0.350833  1.147968                 -0.435486  1.179830          -1.530560   

   high_blood_pressure     platelets  serum_creatinine  serum_sodium  \
0             1.359272  1.681648e-02          0.490057     -1.504036   
1            -0.735688  7.535660e-09         -0.284552     -0.141976   
2            -0.735688 -1.038073e+00         -0.090900     -1.731046   
3            -0.735688 -5.464741e-01          0.490057      0.085034   
4            -0.735688  6.517986e-01          1.264666     -4.682176   

        sex   smoking      time  
0  0.735688 -0.687682 -1.629502  
1  0.735688 -0.687682 -1.603691  
2  0.735688  1.454161 -1.590785  
3  0.735688 -0.687682 -1.590785  
4 -1.359272 -0.687682 -1.577879

In [16]:
X=X[["time","serum_creatinine","ejection_fraction","serum_sodium","high_blood_pressure","creatinine_phosphokinase","anaemia","age"]]
X.head()

time  serum_creatinine  ejection_fraction  serum_sodium  \
0 -1.629502          0.490057          -1.530560     -1.504036   
1 -1.603691         -0.284552          -0.007077     -0.141976   
2 -1.590785         -0.090900          -1.530560     -1.731046   
3 -1.590785          0.490057          -1.530560      0.085034   
4 -1.577879          1.264666          -1.530560     -4.682176   

   high_blood_pressure  creatinine_phosphokinase   anaemia       age  
0             1.359272                  0.000166 -0.871105  1.192945  
1            -0.735688                  7.514640 -0.871105 -0.491279  
2            -0.735688                 -0.449939 -0.871105  0.350833  
3            -0.735688                 -0.486071  1.147968 -0.912335  
4            -0.735688                 -0.435486  1.147968  0.350833

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(239, 8)
(60, 8)


In [18]:
from sklearn.ensemble import GradientBoostingClassifier
gradient=GradientBoostingClassifier(loss="exponential",learning_rate=0.025,n_estimators=210,subsample=0.95,criterion="friedman_mse",min_samples_split=2,min_samples_leaf=2,max_depth=3,max_features="auto",validation_fraction=0.15,random_state=0).fit(X_train,y_train)
gradient

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.025, loss='exponential', max_depth=3,
              max_features='auto', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=2, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=210,
              n_iter_no_change=None, presort='auto', random_state=0,
              subsample=0.95, tol=0.0001, validation_fraction=0.15,
              verbose=0, warm_start=False)

In [19]:
from sklearn.metrics import accuracy_score
y0_pred=gradient.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=gradient.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.9748953974895398
Accuracy for test data is:  0.7666666666666667


In [20]:
from sklearn.metrics import roc_auc_score
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.9618125419181758
AUC for test data is:  0.7257142857142858


In [21]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[167   1]
 [  5  66]]
Confusion matrix for test data is: 
 [[34  1]
 [13 12]]


In [22]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(n_estimators=130,criterion="gini",max_depth=3,min_samples_split=3,min_samples_leaf=1,max_features="sqrt",bootstrap=True,n_jobs=-1,warm_start=False,class_weight="balanced_subsample",random_state=0).fit(X_train,y_train)
forest

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, class_weight='balanced_subsample',
            criterion='gini', max_depth=3, max_features='sqrt',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=3, min_weight_fraction_leaf=0.0,
            n_estimators=130, n_jobs=-1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [23]:
y0_pred=forest.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=forest.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.9372384937238494
Accuracy for test data is:  0.7833333333333333


In [24]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.9268947015425889
AUC for test data is:  0.7571428571428571


In [25]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[160   8]
 [  7  64]]
Confusion matrix for test data is: 
 [[32  3]
 [10 15]]


In [26]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier(criterion="gini",splitter="best",max_depth=3,min_samples_split=3,min_samples_leaf=0.4,max_features="log2",random_state=0).fit(X_train,y_train)
tree

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features='log2', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=0.4, min_samples_split=3,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [27]:
y0_pred=tree.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=tree.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.7573221757322176
Accuracy for test data is:  0.65


In [28]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.7623239436619718
AUC for test data is:  0.6542857142857144


In [29]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[126  42]
 [ 16  55]]
Confusion matrix for test data is: 
 [[22 13]
 [ 8 17]]


In [30]:
from sklearn.naive_bayes import GaussianNB
NB=GaussianNB().fit(X_train,y_train)
NB

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [31]:
y0_pred=NB.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=NB.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.7866108786610879
Accuracy for test data is:  0.7166666666666667


In [32]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.7059020791415158
AUC for test data is:  0.6657142857142856


In [33]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[152  16]
 [ 35  36]]
Confusion matrix for test data is: 
 [[34  1]
 [16  9]]


In [34]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(penalty="l2",C=0.015,class_weight="balanced",solver="saga",max_iter=100,multi_class="multinomial",n_jobs=-1,random_state=0).fit(X_train,y_train)
logistic

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.015, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='multinomial', n_jobs=-1, penalty='l2',
          random_state=0, solver='saga', tol=0.0001, verbose=0,
          warm_start=False)

In [35]:
y0_pred=logistic.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=logistic.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.8368200836820083
Accuracy for test data is:  0.8


In [36]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.8392018779342724
AUC for test data is:  0.7828571428571428


In [37]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[140  28]
 [ 11  60]]
Confusion matrix for test data is: 
 [[31  4]
 [ 8 17]]


In [38]:

from sklearn import svm
svm=svm.SVC(C=0.3,kernel="linear",degree=2,gamma="scale",cache_size=120,decision_function_shape="ovr",random_state=0).fit(X_train,y_train)
svm

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.3, cache_size=120, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma='scale', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [39]:
y0_pred=svm.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=svm.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.8493723849372385
Accuracy for test data is:  0.8


In [40]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.8196680080482897
AUC for test data is:  0.7714285714285715


In [41]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[150  18]
 [ 18  53]]
Confusion matrix for test data is: 
 [[33  2]
 [10 15]]


In [42]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=5,weights="distance",algorithm="auto",leaf_size=10,p=1,n_jobs=-1).fit(X_train,y_train)
KNN

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=10, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=1,
           weights='distance')

In [43]:
y0_pred=KNN.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=KNN.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  1.0
Accuracy for test data is:  0.7333333333333333


In [44]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  1.0
AUC for test data is:  0.6971428571428571


In [45]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[168   0]
 [  0  71]]
Confusion matrix for test data is: 
 [[32  3]
 [13 12]]


In [48]:

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.optimizers import Adam

In [49]:
length=X_test.shape[1]
length

8

In [50]:
from keras.utils import to_categorical
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)
num_classes=y_test.shape[1]
print(num_classes)

2


In [58]:
def classification_model():
    # create model
    model = Sequential()
    model.add(Dense(length, activation='relu', input_shape=(length,)))
    model.add(Dense(120, activation='relu'))
    model.add(Dropout(0.35))
    model.add(Dense(120, activation='relu'))
    model.add(Dropout(0.35))
    model.add(Dense(120, activation='relu'))
    model.add(Dropout(0.35))
    model.add(Dense(120, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    opt=Adam(lr=0.02)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [70]:
model=classification_model()
model.fit(X_train,y_train,validation_data=(X_test, y_test),epochs=25, verbose=2)
model.evaluate(X_test,y_test,verbose=0)

Train on 239 samples, validate on 60 samples
Epoch 1/25
 - 3s - loss: 0.6924 - acc: 0.6234 - val_loss: 0.6575 - val_acc: 0.7167
Epoch 2/25
 - 0s - loss: 0.4865 - acc: 0.7406 - val_loss: 1.0960 - val_acc: 0.6167
Epoch 3/25
 - 0s - loss: 0.4707 - acc: 0.7699 - val_loss: 0.4441 - val_acc: 0.7833
Epoch 4/25
 - 0s - loss: 0.3995 - acc: 0.8159 - val_loss: 0.8367 - val_acc: 0.8000
Epoch 5/25
 - 0s - loss: 0.3134 - acc: 0.8201 - val_loss: 0.8624 - val_acc: 0.7833
Epoch 6/25
 - 0s - loss: 0.3412 - acc: 0.8577 - val_loss: 1.1277 - val_acc: 0.7833
Epoch 7/25
 - 0s - loss: 0.2769 - acc: 0.8326 - val_loss: 1.3732 - val_acc: 0.7833
Epoch 8/25
 - 0s - loss: 0.2913 - acc: 0.8661 - val_loss: 1.2724 - val_acc: 0.7667
Epoch 9/25
 - 0s - loss: 0.3172 - acc: 0.8243 - val_loss: 1.2177 - val_acc: 0.7833
Epoch 10/25
 - 0s - loss: 0.2780 - acc: 0.8577 - val_loss: 1.5315 - val_acc: 0.7833
Epoch 11/25
 - 0s - loss: 0.3371 - acc: 0.8285 - val_loss: 0.8807 - val_acc: 0.7333
Epoch 12/25
 - 0s - loss: 0.3232 - acc: 

[2.3906869411468508, 0.7833333253860474]

In [60]:
y0_pred=model.predict(X_train)
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
y1_pred=model.predict(X_test)
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.9694835680751174
AUC for test data is:  0.8177142857142856


In [61]:
y1_pred=round(pd.DataFrame(y1_pred).rename(columns={0:"Pred_0",1:"Pred_1"}),1)
y1_pred.head()

Pred_0  Pred_1
0     1.0     0.0
1     1.0     0.0
2     0.6     0.4
3     0.0     1.0
4     1.0     0.0

In [62]:
y1_pred["Pred_0"]=np.where((y1_pred.Pred_0 >=0.5),1,y1_pred.Pred_0)
y1_pred["Pred_0"]=np.where((y1_pred.Pred_0 < 0.5),0,y1_pred.Pred_0)
y1_pred["Pred_1"]=np.where((y1_pred.Pred_1 >=0.5),1,y1_pred.Pred_1)
y1_pred["Pred_1"]=np.where((y1_pred.Pred_1 <0.5),0,y1_pred.Pred_1)
y1_pred.head()

Pred_0  Pred_1
0     1.0     0.0
1     1.0     0.0
2     1.0     0.0
3     0.0     1.0
4     1.0     0.0

In [63]:
y1_pred["Pred_0"]=np.where((y1_pred.Pred_0 == y1_pred.Pred_1),0,y1_pred.Pred_0)
y1_pred.head()

Pred_0  Pred_1
0     1.0     0.0
1     1.0     0.0
2     1.0     0.0
3     0.0     1.0
4     1.0     0.0

In [64]:
y_test=pd.DataFrame(y_test).rename(columns={0:"Actual_0",1:"Actual_1"})
y_test.head()

Actual_0  Actual_1
0       1.0       0.0
1       1.0       0.0
2       0.0       1.0
3       0.0       1.0
4       1.0       0.0

In [65]:
len0=len(y_test[y_test["Actual_0"]==1])
print("The number of actual negative cases: ",len0)

The number of actual negative cases:  35


In [66]:
len1=len(y_test[y_test["Actual_1"]==1])
print("The number of actual positive cases: ",len1)

The number of actual positive cases:  25


In [67]:
len00=len(y1_pred[y1_pred["Pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  41


In [68]:
len11=len(y1_pred[y1_pred["Pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  19


In [71]:
print("Confusion matrix for test data: \n",np.array([[32,3],[9,16]]))

Confusion matrix for test data: 
 [[32  3]
 [ 9 16]]
