In [86]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_da66db362611452c986019d15531a283.csv"
df=pd.read_csv(url)
df.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [87]:
df.shape

(299, 13)

In [88]:
df.isna().any()

age                         False
anaemia                     False
creatinine_phosphokinase    False
diabetes                    False
ejection_fraction           False
high_blood_pressure         False
platelets                   False
serum_creatinine            False
serum_sodium                False
sex                         False
smoking                     False
time                        False
DEATH_EVENT                 False
dtype: bool

In [89]:
df.groupby("DEATH_EVENT").count().T

DEATH_EVENT                 0   1
age                       203  96
anaemia                   203  96
creatinine_phosphokinase  203  96
diabetes                  203  96
ejection_fraction         203  96
high_blood_pressure       203  96
platelets                 203  96
serum_creatinine          203  96
serum_sodium              203  96
sex                       203  96
smoking                   203  96
time                      203  96

In [90]:
X=df.drop(["DEATH_EVENT"],axis=1)
X.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  
0        0     4  
1        0     6  
2        1     7  
3        0     7  
4        0     8

In [91]:
y=df[["DEATH_EVENT"]]
y.head()

DEATH_EVENT
0            1
1            1
2            1
3            1
4            1

In [92]:
import numpy as  np
np.unique(y)

array([0, 1])

In [93]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)
X.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


age   anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  1.192945 -0.871105                  0.000166 -0.847579          -1.530560   
1 -0.491279 -0.871105                  7.514640 -0.847579          -0.007077   
2  0.350833 -0.871105                 -0.449939 -0.847579          -1.530560   
3 -0.912335  1.147968                 -0.486071 -0.847579          -1.530560   
4  0.350833  1.147968                 -0.435486  1.179830          -1.530560   

   high_blood_pressure     platelets  serum_creatinine  serum_sodium  \
0             1.359272  1.681648e-02          0.490057     -1.504036   
1            -0.735688  7.535660e-09         -0.284552     -0.141976   
2            -0.735688 -1.038073e+00         -0.090900     -1.731046   
3            -0.735688 -5.464741e-01          0.490057      0.085034   
4            -0.735688  6.517986e-01          1.264666     -4.682176   

        sex   smoking      time  
0  0.735688 -0.687682 -1.629502  
1  0.735688 -0.687682 -1.603691  
2  0.735688  1.454161 -1.590785  
3  0.735688 -0.687682 -1.590785  
4 -1.359272 -0.687682 -1.577879

In [94]:
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif

test = SelectKBest(score_func=mutual_info_classif, k="all")
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
# summarize scores
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores1=scores.sort_values(by=["scores"],ascending=False)
scores1

scores
11  0.251165
7   0.116570
4   0.034101
8   0.028712
5   0.025189
2   0.023625
1   0.022689
0   0.015449
3   0.000000
6   0.000000
9   0.000000
10  0.000000

In [95]:
from sklearn.feature_selection import f_classif

test = SelectKBest(score_func=f_classif, k="all")
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
# summarize scores
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores2=scores.sort_values(by=["scores"],ascending=False)
scores2

scores
11  114.181264
7    28.158492
4    23.094063
0    20.435946
8    11.765331
5     1.881937
1     1.310096
2     1.173259
6     0.718880
10    0.047333
9     0.005534
3     0.001121

In [96]:
scores1=scores1[scores1["scores"]>0]
X=X.iloc[:,scores1.index]
X.head()

time  serum_creatinine  ejection_fraction  serum_sodium  \
0 -1.629502          0.490057          -1.530560     -1.504036   
1 -1.603691         -0.284552          -0.007077     -0.141976   
2 -1.590785         -0.090900          -1.530560     -1.731046   
3 -1.590785          0.490057          -1.530560      0.085034   
4 -1.577879          1.264666          -1.530560     -4.682176   

   high_blood_pressure  creatinine_phosphokinase   anaemia       age  
0             1.359272                  0.000166 -0.871105  1.192945  
1            -0.735688                  7.514640 -0.871105 -0.491279  
2            -0.735688                 -0.449939 -0.871105  0.350833  
3            -0.735688                 -0.486071  1.147968 -0.912335  
4            -0.735688                 -0.435486  1.147968  0.350833

In [97]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(239, 8)
(60, 8)


In [98]:
df_t=pd.concat([X_train,y_train],axis=1)

In [99]:
df_t0=df_t[df_t["DEATH_EVENT"]==0]
df_t1=df_t[df_t["DEATH_EVENT"]==1]
df_t1=pd.concat([df_t1]*2,axis=0)

In [100]:
df_t=pd.concat([df_t0,df_t1],axis=0)
df_t.shape

(310, 9)

In [101]:
X_train=df_t.drop(["DEATH_EVENT"],axis=1)
X_train.shape

(310, 8)

In [102]:
y_train=df_t[["DEATH_EVENT"]]
y_train.shape

(310, 1)

In [297]:
from sklearn.ensemble import GradientBoostingClassifier
gradient=GradientBoostingClassifier(loss="exponential",learning_rate=0.025,n_estimators=210,subsample=0.95,criterion="friedman_mse",min_samples_split=2,min_samples_leaf=2,max_depth=3,max_features="auto",validation_fraction=0.15,random_state=0).fit(X_train,y_train)
gradient

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.025, loss='exponential', max_depth=3,
              max_features='auto', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=2, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=210,
              n_iter_no_change=None, presort='auto', random_state=0,
              subsample=0.95, tol=0.0001, validation_fraction=0.15,
              verbose=0, warm_start=False)

In [298]:
from sklearn.metrics import accuracy_score
y0_pred=gradient.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=gradient.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.9806451612903225
Accuracy for test data is:  0.7833333333333333


In [299]:
from sklearn.metrics import roc_auc_score
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.9810529845741113
AUC for test data is:  0.7685714285714287


In [300]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[164   4]
 [  2 140]]
Confusion matrix for test data is: 
 [[30  5]
 [ 8 17]]


In [301]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(n_estimators=130,criterion="gini",max_depth=3,min_samples_split=3,min_samples_leaf=1,max_features="sqrt",bootstrap=True,n_jobs=-1,warm_start=False,class_weight="balanced_subsample",random_state=0).fit(X_train,y_train)
forest

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, class_weight='balanced_subsample',
            criterion='gini', max_depth=3, max_features='sqrt',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=3, min_weight_fraction_leaf=0.0,
            n_estimators=130, n_jobs=-1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [302]:
y0_pred=forest.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=forest.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.9161290322580645
Accuracy for test data is:  0.8166666666666667


In [303]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.9139000670690812
AUC for test data is:  0.7971428571428572


In [304]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[158  10]
 [ 16 126]]
Confusion matrix for test data is: 
 [[32  3]
 [ 8 17]]


In [333]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier(criterion="gini",splitter="best",max_depth=3,min_samples_split=3,min_samples_leaf=0.4,max_features="log2",random_state=0).fit(X_train,y_train)
tree

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features='log2', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=0.4, min_samples_split=3,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [334]:
y0_pred=tree.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=tree.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.7838709677419354
Accuracy for test data is:  0.75


In [335]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.777707914151576
AUC for test data is:  0.7342857142857142


In [336]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[143  25]
 [ 42 100]]
Confusion matrix for test data is: 
 [[29  6]
 [ 9 16]]


In [337]:
from sklearn.naive_bayes import GaussianNB
NB=GaussianNB().fit(X_train,y_train)
NB

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [338]:
y0_pred=NB.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=NB.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.8064516129032258
Accuracy for test data is:  0.75


In [339]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.7996311200536552
AUC for test data is:  0.7057142857142857


In [340]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[148  20]
 [ 40 102]]
Confusion matrix for test data is: 
 [[34  1]
 [14 11]]


In [371]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(penalty="l2",C=0.015,class_weight="balanced",solver="saga",max_iter=100,multi_class="multinomial",n_jobs=-1,random_state=0).fit(X_train,y_train)
logistic

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.015, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='multinomial', n_jobs=-1, penalty='l2',
          random_state=0, solver='saga', tol=0.0001, verbose=0,
          warm_start=False)

In [372]:
y0_pred=logistic.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=logistic.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.8387096774193549
Accuracy for test data is:  0.7833333333333333


In [373]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.8392018779342724
AUC for test data is:  0.7685714285714287


In [374]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[140  28]
 [ 22 120]]
Confusion matrix for test data is: 
 [[30  5]
 [ 8 17]]


In [431]:

from sklearn import svm
svm=svm.SVC(C=0.3,kernel="linear",degree=2,gamma="scale",cache_size=120,decision_function_shape="ovr",random_state=0).fit(X_train,y_train)
svm

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.3, cache_size=120, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma='scale', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [432]:
y0_pred=svm.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=svm.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  0.8419354838709677
Accuracy for test data is:  0.8


In [433]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.8410881958417169
AUC for test data is:  0.7828571428571428


In [434]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[143  25]
 [ 24 118]]
Confusion matrix for test data is: 
 [[31  4]
 [ 8 17]]


In [468]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=5,weights="distance",algorithm="auto",leaf_size=10,p=1,n_jobs=-1).fit(X_train,y_train)
KNN

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=10, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=1,
           weights='distance')

In [469]:
y0_pred=KNN.predict(X_train)
print("Accuracy for train data is: ",accuracy_score(y_train,y0_pred))
y1_pred=KNN.predict(X_test)
print("Accuracy for test data is: ", accuracy_score(y_test,y1_pred))

Accuracy for train data is:  1.0
Accuracy for test data is:  0.7666666666666667


In [470]:
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  1.0
AUC for test data is:  0.7371428571428572


In [471]:
print("Confusion matrix for for train data is: \n",confusion_matrix(y_train,y0_pred))
print("Confusion matrix for test data is: \n", confusion_matrix(y_test,y1_pred))

Confusion matrix for for train data is: 
 [[168   0]
 [  0 142]]
Confusion matrix for test data is: 
 [[32  3]
 [11 14]]


In [473]:

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.optimizers import Adam

In [474]:
length=X_test.shape[1]
length

8

In [475]:
from keras.utils import to_categorical
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)
num_classes=y_test.shape[1]
print(num_classes)

2


In [506]:
def classification_model():
    # create model
    model = Sequential()
    model.add(Dense(length, activation='relu', input_shape=(length,)))
    model.add(Dense(120, activation='relu'))
    model.add(Dropout(0.35))
    model.add(Dense(120, activation='relu'))
    model.add(Dropout(0.35))
    model.add(Dense(120, activation='relu'))
    model.add(Dropout(0.35))
    model.add(Dense(120, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    opt=Adam(lr=0.02)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [507]:
model=classification_model()
model.fit(X_train,y_train,validation_data=(X_test, y_test),epochs=25, verbose=2)
model.evaluate(X_test,y_test,verbose=0)

Train on 310 samples, validate on 60 samples
Epoch 1/25
 - 4s - loss: 0.9479 - acc: 0.6226 - val_loss: 0.6139 - val_acc: 0.6667
Epoch 2/25
 - 0s - loss: 0.5255 - acc: 0.7742 - val_loss: 0.5301 - val_acc: 0.7500
Epoch 3/25
 - 0s - loss: 0.4189 - acc: 0.8387 - val_loss: 0.8541 - val_acc: 0.7333
Epoch 4/25
 - 0s - loss: 0.3619 - acc: 0.8548 - val_loss: 1.0926 - val_acc: 0.7500
Epoch 5/25
 - 0s - loss: 0.3375 - acc: 0.8871 - val_loss: 1.1256 - val_acc: 0.7333
Epoch 6/25
 - 0s - loss: 0.2910 - acc: 0.8806 - val_loss: 1.2667 - val_acc: 0.7500
Epoch 7/25
 - 0s - loss: 0.3082 - acc: 0.8710 - val_loss: 0.8802 - val_acc: 0.7000
Epoch 8/25
 - 0s - loss: 0.3435 - acc: 0.8710 - val_loss: 1.3285 - val_acc: 0.7500
Epoch 9/25
 - 0s - loss: 0.2794 - acc: 0.8742 - val_loss: 0.9991 - val_acc: 0.7333
Epoch 10/25
 - 0s - loss: 0.3193 - acc: 0.8710 - val_loss: 1.3886 - val_acc: 0.7500
Epoch 11/25
 - 0s - loss: 0.2789 - acc: 0.8839 - val_loss: 1.2251 - val_acc: 0.7333
Epoch 12/25
 - 0s - loss: 0.3000 - acc: 

[1.717195494969686, 0.799999992052714]

In [508]:
y0_pred=model.predict(X_train)
print("AUC for train data is: ",roc_auc_score(y_train,y0_pred))
y1_pred=model.predict(X_test)
print("AUC for test data is: ", roc_auc_score(y_test,y1_pred))

AUC for train data is:  0.9731723675385647
AUC for test data is:  0.8505714285714285


In [509]:
y1_pred=round(pd.DataFrame(y1_pred).rename(columns={0:"Pred_0",1:"Pred_1"}),1)
y1_pred.head()

Pred_0  Pred_1
0     1.0     0.0
1     1.0     0.0
2     0.3     0.7
3     0.0     1.0
4     1.0     0.0

In [510]:
y1_pred["Pred_0"]=np.where((y1_pred.Pred_0 >=0.5),1,y1_pred.Pred_0)
y1_pred["Pred_0"]=np.where((y1_pred.Pred_0 < 0.5),0,y1_pred.Pred_0)
y1_pred["Pred_1"]=np.where((y1_pred.Pred_1 >=0.5),1,y1_pred.Pred_1)
y1_pred["Pred_1"]=np.where((y1_pred.Pred_1 <0.5),0,y1_pred.Pred_1)
y1_pred.head()

Pred_0  Pred_1
0     1.0     0.0
1     1.0     0.0
2     0.0     1.0
3     0.0     1.0
4     1.0     0.0

In [511]:
y1_pred["Pred_0"]=np.where((y1_pred.Pred_0 == y1_pred.Pred_1),0,y1_pred.Pred_0)
y1_pred.head()

Pred_0  Pred_1
0     1.0     0.0
1     1.0     0.0
2     0.0     1.0
3     0.0     1.0
4     1.0     0.0

In [512]:
y_test=pd.DataFrame(y_test).rename(columns={0:"Actual_0",1:"Actual_1"})
y_test.head()

Actual_0  Actual_1
0       1.0       0.0
1       1.0       0.0
2       0.0       1.0
3       0.0       1.0
4       1.0       0.0

In [513]:
len0=len(y_test[y_test["Actual_0"]==1])
print("The number of actual negative cases: ",len0)

The number of actual negative cases:  35


In [514]:
len1=len(y_test[y_test["Actual_1"]==1])
print("The number of actual positive cases: ",len1)

The number of actual positive cases:  25


In [515]:
len00=len(y1_pred[y1_pred["Pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  39


In [516]:
len11=len(y1_pred[y1_pred["Pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  21


In [517]:
print("Confusion matrix for test data: \n",np.array([[31,4],[8,17]]))

Confusion matrix for test data: 
 [[31  4]
 [ 8 17]]
