In [3]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_820bb99c09934d7d9ebc132e45af625a.csv"
df=pd.read_csv(url,header=None)
df.head()

0          1                                                  2
0  +        S10  tactagcaatacgcttgcgttcggtggttaagtatgtataatgcgc...
1  +       AMPC  tgctatcctgacagttgtcacgctgattggtgtcgttacaatctaa...
2  +       AROH  gtactagagaactagtgcattagcttatttttttgttatcatgcta...
3  +      DEOP2  aattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaata...
4  +  LEU1_TRNA  tcgataattaactattgacgaaaagctgaaaaccactagaatgcgc...

In [4]:
df.shape

(106, 3)

In [5]:
def listToString(s):  
    str1 = " "   
    return (str1.join(s)) 

In [6]:
dna=pd.DataFrame(df.iloc[:,2])

In [7]:
import numpy as np
for i in np.arange(0,106):
    string=listToString(dna.loc[i].tolist())
    print(string)

tactagcaatacgcttgcgttcggtggttaagtatgtataatgcgcgggcttgtcgt
tgctatcctgacagttgtcacgctgattggtgtcgttacaatctaacgcatcgccaa
gtactagagaactagtgcattagcttatttttttgttatcatgctaaccacccggcg
aattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaatactaacaaactc
tcgataattaactattgacgaaaagctgaaaaccactagaatgcgcctccgtggtag
aggggcaaggaggatggaaagaggttgccgtataaagaaactagagtccgtttaggt
cagggggtggaggatttaagccatctcctgatgacgcatagtcagcccatcatgaat
tttctacaaaacacttgatactgtatgagcatacagtataattgcttcaacagaaca
cgacttaatatactgcgacaggacgtccgttctgtgtaaatcgcaatgaaatggttt
ttttaaatttcctcttgtcaggccggaataactccctataatgcgccaccactgaca
gcaaaaataaatgcttgactctgtagcgggaaggcgtattatgcacaccccgcgccg
cctgaaattcagggttgactctgaaagaggaaagcgtaatatacgccacctcgcgac
gatcaaaaaaatacttgtgcaaaaaattgggatccctataatgcgcctccgttgaga
ctgcaatttttctattgcggcctgcggagaactccctataatgcgcctccatcgaca
tttatatttttcgcttgtcaggccggaataactccctataatgcgccaccactgaca
aagcaaagaaatgcttgactctgtagcgggaaggcgtattatgcacaccgccgcgcc
atgcatttttccgcttgtcttcctgagccgactccctataatgcgcctccatcgaca
aaacaatttcagaa

In [8]:
import numpy as np
dinucleotides = ['aa','at','ag','ac',
                 'ta','tt','tg','tc',
                 'ga','gt','gg','gc',
                 'ca','ct','cg','cc']
all_counts = []
for i in np.arange(0,106):
    string=listToString(dna.loc[i].tolist())
    for dinucleotide in dinucleotides:
        count = string.count(dinucleotide)
        print("count is " + str(count) + " for " + dinucleotide)
        all_counts.append(count)
print(all_counts)

count is 3 for aa
count is 4 for at
count is 2 for ag
count is 2 for ac
count is 7 for ta
count is 4 for tt
count is 5 for tg
count is 2 for tc
count is 0 for ga
count is 7 for gt
count is 3 for gg
count is 6 for gc
count is 1 for ca
count is 3 for ct
count is 6 for cg
count is 0 for cc
count is 3 for aa
count is 4 for at
count is 1 for ag
count is 4 for ac
count is 3 for ta
count is 3 for tt
count is 6 for tg
count is 5 for tc
count is 2 for ga
count is 5 for gt
count is 1 for gg
count is 4 for gc
count is 5 for ca
count is 4 for ct
count is 4 for cg
count is 2 for cc
count is 2 for aa
count is 4 for at
count is 4 for ag
count is 4 for ac
count is 7 for ta
count is 6 for tt
count is 3 for tg
count is 1 for tc
count is 2 for ga
count is 3 for gt
count is 1 for gg
count is 4 for gc
count is 3 for ca
count is 4 for ct
count is 2 for cg
count is 2 for cc
count is 5 for aa
count is 5 for at
count is 4 for ag
count is 3 for ac
count is 5 for ta
count is 3 for tt
count is 8 for tg
count is 2

count is 2 for ca
count is 5 for ct
count is 4 for cg
count is 1 for cc
count is 0 for aa
count is 3 for at
count is 4 for ag
count is 2 for ac
count is 0 for ta
count is 3 for tt
count is 3 for tg
count is 6 for tc
count is 4 for ga
count is 5 for gt
count is 4 for gg
count is 5 for gc
count is 5 for ca
count is 2 for ct
count is 6 for cg
count is 3 for cc
count is 3 for aa
count is 5 for at
count is 1 for ag
count is 3 for ac
count is 6 for ta
count is 2 for tt
count is 4 for tg
count is 6 for tc
count is 1 for ga
count is 6 for gt
count is 3 for gg
count is 1 for gc
count is 2 for ca
count is 5 for ct
count is 3 for cg
count is 4 for cc
count is 4 for aa
count is 3 for at
count is 2 for ag
count is 4 for ac
count is 3 for ta
count is 0 for tt
count is 5 for tg
count is 4 for tc
count is 4 for ga
count is 4 for gt
count is 5 for gg
count is 4 for gc
count is 2 for ca
count is 4 for ct
count is 6 for cg
count is 2 for cc
count is 3 for aa
count is 4 for at
count is 2 for ag
count is 6

In [9]:
all_counts=np.asarray(all_counts).reshape(106,16)
all_counts

array([[3, 4, 2, ..., 3, 6, 0],
       [3, 4, 1, ..., 4, 4, 2],
       [2, 4, 4, ..., 4, 2, 2],
       ...,
       [1, 3, 3, ..., 5, 4, 4],
       [4, 1, 3, ..., 6, 2, 2],
       [9, 7, 4, ..., 4, 0, 1]])

In [10]:
X=pd.DataFrame(all_counts)
X

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
0     3   4   2   2   7   4   5   2   0   7   3   6   1   3   6   0
1     3   4   1   4   3   3   6   5   2   5   1   4   5   4   4   2
2     2   4   4   4   7   6   3   1   2   3   1   4   3   4   2   2
3     5   5   4   3   5   3   8   2   5   8   1   1   1   2   2   0
4     7   4   3   4   5   2   4   2   5   2   1   3   1   4   4   3
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
101   4   3   3   2   3   4   4   3   4   2   6   2   1   6   1   2
102   5   6   2   5   2   5   3   6   5   3   2   0   6   2   3   1
103   1   3   3   4   2   4   6   3   6   3   2   4   2   5   4   4
104   4   1   3   2   1   4   4   5   4   3   6   2   1   6   2   2
105   9   7   4   3   6   2   1   4   2   0   3   3   6   4   0   1

[106 rows x 16 columns]

In [77]:
df=df.rename(columns={0:"Class"})
y=df[["Class"]]
y.groupby("Class")["Class"].count()

Class
+    53
-    53
Name: Class, dtype: int64

In [12]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X))
X

0         1         2         3         4         5         6   \
0   -0.130777  0.023564 -0.519584 -1.090041  2.017797  0.170093  0.560806   
1   -0.130777  0.023564 -1.049161  0.310497 -0.412731 -0.345047  1.173646   
2   -0.644198  0.023564  0.539569  0.310497  2.017797  1.200373 -0.664873   
3    0.896065  0.648001  0.539569 -0.389772  0.802533 -0.345047  2.399325   
4    1.922907  0.023564  0.009992  0.310497  0.802533 -0.860187 -0.052034   
..        ...       ...       ...       ...       ...       ...       ...   
101  0.382644 -0.600874  0.009992 -1.090041 -0.412731  0.170093 -0.052034   
102  0.896065  1.272439 -0.519584  1.010766 -1.020363  0.685233 -0.664873   
103 -1.157619 -0.600874  0.009992  0.310497 -1.020363  0.170093  1.173646   
104  0.382644 -1.849749  0.009992 -1.090041 -1.627995  0.170093 -0.052034   
105  2.949749  1.896876  0.539569 -0.389772  1.410165 -0.860187 -1.890552   

           7         8         9         10        11        12        13  \
0   -0.872143 -1.831687  2.257951  0.574902  1.297106 -1.510693 -0.581787   
1    1.108867 -0.807102  1.036814 -0.694673  0.289830  1.169365  0.161218   
2   -1.532480 -0.807102 -0.184323 -0.694673  0.289830 -0.170664  0.161218   
3   -0.872143  0.729775  2.868519 -0.694673 -1.221085 -1.510693 -1.324792   
4   -0.872143  0.729775 -0.794891 -0.694673 -0.213809 -1.510693  0.161218   
..        ...       ...       ...       ...       ...       ...       ...   
101 -0.211806  0.217483 -0.794891  2.479264 -0.717447 -1.510693  1.647228   
102  1.769204  0.729775 -0.184323 -0.059886 -1.724723  1.839379 -1.324792   
103 -0.211806  1.242068 -0.184323 -0.059886  0.289830 -0.840678  0.904223   
104  1.108867  0.217483 -0.184323  2.479264 -0.717447 -1.510693  1.647228   
105  0.448531 -0.807102 -2.016027  0.574902 -0.213809  1.839379  0.161218   

           14        15  
0    1.478443 -1.678517  
1    0.359050 -0.144700  
2   -0.760342 -0.144700  
3   -0.760342 -1.678517  
4    0.359050  0.622209  
..        ...       ...  
101 -1.320038 -0.144700  
102 -0.200646 -0.911609  
103  0.359050  1.389118  
104 -0.760342 -0.144700  
105 -1.879734 -0.911609  

[106 rows x 16 columns]

In [13]:
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [14]:
from sklearn import svm
model1=svm.SVC(random_state=0)
scores=cross_val_score(model1,X,np.asarray(y).reshape(y.shape[0],),cv=5)
print("Accuracy is: ",scores.mean(), "+/-",scores.std())

Accuracy is:  0.8969696969696969 +/- 0.05290602984399023


In [15]:
y_pred = cross_val_predict(model1, X, np.asarray(y).reshape(y.shape[0],), cv=5)
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[48  5]
 [ 6 47]]


In [16]:
print("Classification report: \n",classification_report(y,y_pred))

Classification report: 
               precision    recall  f1-score   support

           +       0.89      0.91      0.90        53
           -       0.90      0.89      0.90        53

    accuracy                           0.90       106
   macro avg       0.90      0.90      0.90       106
weighted avg       0.90      0.90      0.90       106



In [17]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier(n_estimators=100,random_state=0)
scores=cross_val_score(model2,X,np.asarray(y).reshape(y.shape[0],),cv=5)
print("Accuracy is: ",scores.mean(), "+/-",scores.std())

Accuracy is:  0.8398268398268398 +/- 0.03693632728606327


In [18]:
y_pred = cross_val_predict(model2, X, np.asarray(y).reshape(y.shape[0],), cv=5)
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[44  9]
 [ 8 45]]


In [19]:
print("Classification report: \n",classification_report(y,y_pred))

Classification report: 
               precision    recall  f1-score   support

           +       0.85      0.83      0.84        53
           -       0.83      0.85      0.84        53

    accuracy                           0.84       106
   macro avg       0.84      0.84      0.84       106
weighted avg       0.84      0.84      0.84       106



In [20]:
from sklearn.ensemble import GradientBoostingClassifier
model3=GradientBoostingClassifier(n_estimators=150,max_features="sqrt",random_state=0)
scores=cross_val_score(model3,X,np.asarray(y).reshape(y.shape[0],),cv=5)
print("Accuracy is: ",scores.mean(), "+/-",scores.std())

Accuracy is:  0.8112554112554111 +/- 0.0034632034632034792


In [21]:
from sklearn.neighbors import KNeighborsClassifier
model4=KNeighborsClassifier(n_neighbors=3)
scores=cross_val_score(model4,X,np.asarray(y).reshape(y.shape[0],),cv=4)
print("Accuracy is: ",scores.mean(), "+/-",scores.std())

Accuracy is:  0.8774928774928775 +/- 0.031013591249397794


In [22]:
from sklearn.naive_bayes import GaussianNB
model5=GaussianNB()
scores=cross_val_score(model5,X,np.asarray(y).reshape(y.shape[0],),cv=5)
print("Accuracy is: ",scores.mean(), "+/-",scores.std())

Accuracy is:  0.8112554112554113 +/- 0.07975713214148245


In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)
print(X_train.shape)
print(X_test.shape)

(79, 16)
(27, 16)


In [24]:
model6=svm.SVC(random_state=0).fit(X_train,np.asarray(y_train).reshape(y_train.shape[0],))
model6

SVC(random_state=0)

In [25]:
from sklearn.metrics import accuracy_score
train_pred=model6.predict(X_train)
test_pred=model6.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,train_pred))
print("Accuracy on test data: ",accuracy_score(y_test,test_pred))

Accuracy on train data:  0.9493670886075949
Accuracy on test data:  0.8888888888888888


In [26]:
classes = df.iloc[:,0]
print(classes[:5])

0    +
1    +
2    +
3    +
4    +
Name: Class, dtype: object


In [27]:
# generate list of DNA sequences
sequences = list(df.iloc[:, 2])
dataset = {}

# loop through sequences and split into individual nucleotides
for i, seq in enumerate(sequences):
    
    # split into nucleotides, remove tab characters
    nucleotides = list(seq)
    nucleotides = [x for x in nucleotides if x != '\t']
    
    # append class assignment
    nucleotides.append(classes[i])
    
    # add to dataset
    dataset[i] = nucleotides
    
print(dataset[0])

['t', 'a', 'c', 't', 'a', 'g', 'c', 'a', 'a', 't', 'a', 'c', 'g', 'c', 't', 't', 'g', 'c', 'g', 't', 't', 'c', 'g', 'g', 't', 'g', 'g', 't', 't', 'a', 'a', 'g', 't', 'a', 't', 'g', 't', 'a', 't', 'a', 'a', 't', 'g', 'c', 'g', 'c', 'g', 'g', 'g', 'c', 't', 't', 'g', 't', 'c', 'g', 't', '+']


In [28]:
X = pd.DataFrame(dataset)
X

0   1   2   3   4   5   6   7   8   9    ... 96  97  98  99  100 101 102  \
0    t   t   g   a   t   a   c   t   c   t  ...   c   c   t   a   g   c   g   
1    a   g   t   a   c   g   a   t   g   t  ...   c   g   a   g   a   c   t   
2    c   c   a   t   g   g   g   t   a   t  ...   g   c   t   a   g   t   a   
3    t   t   c   t   a   g   g   c   c   t  ...   a   t   g   g   a   c   t   
4    a   a   t   g   t   g   g   t   t   a  ...   g   a   a   g   g   a   t   
5    g   t   a   t   a   c   g   a   t   a  ...   t   g   c   g   c   a   c   
6    c   c   g   g   a   a   g   c   a   a  ...   a   g   c   t   a   t   t   
7    a   c   a   a   t   a   t   a   a   t  ...   g   a   g   g   t   g   c   
8    a   t   g   t   t   g   g   a   t   t  ...   a   c   a   t   g   g   a   
9    t   g   a   g   a   g   g   a   a   t  ...   c   t   a   a   t   c   a   
10   a   a   a   t   a   a   a   a   t   c  ...   c   t   c   c   c   c   c   
11   c   c   c   g   c   g   g   c   a   c  ...   c   t   g   t   a   t   a   
12   g   a   t   t   t   g   g   a   c   t  ...   t   c   a   c   g   c   a   
13   c   g   a   a   a   a   a   c   t   c  ...   t   t   g   c   c   t   g   
14   t   t   g   t   t   t   t   t   g   t  ...   a   t   t   a   c   a   a   
15   t   t   t   c   t   g   t   t   c   t  ...   g   g   c   a   t   a   t   
16   g   g   g   g   g   g   t   g   g   g  ...   a   t   a   g   c   a   t   
17   c   t   c   a   a   a   a   a   a   t  ...   g   t   a   a   g   c   a   
18   g   c   a   a   c   a   a   t   c   c  ...   a   g   t   a   a   g   a   
19   t   a   t   g   g   a   g   a   a   a  ...   g   a   c   g   c   g   c   
20   t   c   t   t   a   g   c   c   g   g  ...   c   t   a   a   a   g   c   
21   c   g   a   g   a   a   c   t   g   g  ...   a   t   g   g   a   t   g   
22   g   c   g   t   a   g   a   g   a   c  ...   t   t   a   g   c   c   a   
23   g   t   c   g   a   g   t   t   c   c  ...   g   t   c   a   t   t   c   
24   t   g   t   t   g   t   c   a   g   g  ...   t   c   c   a   t   t   a   
25   g   a   t   t   c   t   t   t   t   g  ...   c   c   g   g   g   g   g   
26   g   t   a   g   t   g   c   g   c   a  ...   a   a   c   a   c   a   a   
27   t   t   t   c   g   c   c   a   c   a  ...   g   t   t   t   a   g   t   
28   t   g   t   g   a   c   t   g   g   t  ...   c   g   t   g   t   g   t   
29   a   g   t   g   a   g   g   c   t   a  ...   c   c   t   a   a   g   c   
30   a   t   t   a   a   t   a   a   t   a  ...   t   g   g   g   a   g   a   
31   g   g   t   g   a   a   t   t   c   c  ...   c   g   a   g   a   t   a   
32   t   t   t   t   c   t   g   a   t   t  ...   g   t   c   c   t   t   t   
33   a   c   t   a   c   a   a   c   g   c  ...   a   g   t   t   g   t   c   
34   t   g   g   g   a   a   c   a   t   c  ...   c   t   c   a   c   t   t   
35   g   t   t   a   c   a   g   g   g   c  ...   a   t   t   g   t   t   c   
36   t   t   t   t   t   g   c   t   t   t  ...   a   t   g   a   t   t   g   
37   a   a   a   g   a   a   a   a   a   a  ...   c   t   g   c   t   g   t   
38   t   c   t   t   g   a   t   t   a   t  ...   t   g   t   g   c   c   g   
39   a   a   c   t   a   a   a   a   a   a  ...   t   c   a   t   t   t   g   
40   a   a   a   a   a   c   g   a   t   a  ...   g   g   t   c   t   g   a   
41   t   t   t   g   t   t   t   t   c   t  ...   c   c   t   t   g   a   t   
42   g   c   g   a   g   a   c   t   g   g  ...   a   a   a   c   t   a   g   
43   c   t   c   a   c   g   a   g   c   c  ...   t   a   c   t   a   a   g   
44   g   a   t   t   g   a   g   c   a   g  ...   a   t   t   g   g   g   a   
45   c   a   a   a   c   g   c   t   a   c  ...   a   g   g   c   a   g   c   
46   g   c   a   c   c   t   c   t   t   c  ...   a   t   t   a   c   a   g   
47   g   g   c   t   t   c   c   c   g   a  ...   t   t   g   t   g   g   t   
48   g   c   c   a   c   c   a   a   a   c  ...   g   a   a   g   t   g   t   
49   c   a   a   a   c   g   t   a   a   c  ...   c  

In [29]:
X=X.transpose()
X

0  1  2  3  4  5  6  7  8  9   ... 48 49 50 51 52 53 54 55 56 57
0    t  a  c  t  a  g  c  a  a  t  ...  g  c  t  t  g  t  c  g  t  +
1    t  g  c  t  a  t  c  c  t  g  ...  c  a  t  c  g  c  c  a  a  +
2    g  t  a  c  t  a  g  a  g  a  ...  c  a  c  c  c  g  g  c  g  +
3    a  a  t  t  g  t  g  a  t  g  ...  a  a  c  a  a  a  c  t  c  +
4    t  c  g  a  t  a  a  t  t  a  ...  c  c  g  t  g  g  t  a  g  +
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
101  c  c  t  c  a  a  t  g  g  c  ...  g  a  a  c  t  a  t  a  t  -
102  g  t  a  t  t  c  t  c  a  a  ...  t  c  a  a  c  a  t  t  g  -
103  c  g  c  g  a  c  t  a  c  g  ...  a  a  g  g  c  t  t  c  c  -
104  c  t  c  g  t  c  c  t  c  a  ...  a  g  g  a  g  g  a  a  c  -
105  t  a  a  c  a  t  t  a  a  t  ...  t  c  a  a  g  a  a  c  t  -

[106 rows x 58 columns]

In [30]:
X=X.iloc[:,0:57]
X

0  1  2  3  4  5  6  7  8  9   ... 47 48 49 50 51 52 53 54 55 56
0    t  a  c  t  a  g  c  a  a  t  ...  g  g  c  t  t  g  t  c  g  t
1    t  g  c  t  a  t  c  c  t  g  ...  g  c  a  t  c  g  c  c  a  a
2    g  t  a  c  t  a  g  a  g  a  ...  c  c  a  c  c  c  g  g  c  g
3    a  a  t  t  g  t  g  a  t  g  ...  t  a  a  c  a  a  a  c  t  c
4    t  c  g  a  t  a  a  t  t  a  ...  t  c  c  g  t  g  g  t  a  g
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
101  c  c  t  c  a  a  t  g  g  c  ...  g  g  a  a  c  t  a  t  a  t
102  g  t  a  t  t  c  t  c  a  a  ...  t  t  c  a  a  c  a  t  t  g
103  c  g  c  g  a  c  t  a  c  g  ...  c  a  a  g  g  c  t  t  c  c
104  c  t  c  g  t  c  c  t  c  a  ...  a  a  g  g  a  g  g  a  a  c
105  t  a  a  c  a  t  t  a  a  t  ...  a  t  c  a  a  g  a  a  c  t

[106 rows x 57 columns]

In [31]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(handle_unknown="ignore")
X=pd.DataFrame(enc.fit_transform(X).toarray())
X

0    1    2    3    4    5    6    7    8    9    ...  218  219  220  \
0    0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  ...  0.0  0.0  1.0   
2    0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  ...  1.0  0.0  0.0   
3    1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
101  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0   
102  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  ...  0.0  1.0  0.0   
103  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  ...  0.0  1.0  0.0   
104  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  0.0  1.0   
105  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   

     221  222  223  224  225  226  227  
0    0.0  1.0  0.0  0.0  0.0  0.0  1.0  
1    0.0  0.0  0.0  1.0  0.0  0.0  0.0  
2    1.0  0.0  0.0  0.0  0.0  1.0  0.0  
3    0.0  0.0  1.0  0.0  1.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  1.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
101  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
102  0.0  0.0  1.0  0.0  0.0  1.0  0.0  
103  1.0  0.0  0.0  0.0  1.0  0.0  0.0  
104  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
105  1.0  0.0  0.0  0.0  0.0  0.0  1.0  

[106 rows x 228 columns]

In [32]:
model7=svm.SVC(kernel="linear",random_state=0)
scores=cross_val_score(model7,X,np.asarray(y).reshape(y.shape[0],),cv=7)
print("Accuracy is: ",scores.mean(), "+/-",scores.std())

Accuracy is:  0.9333333333333333 +/- 0.06172133998483675


In [33]:
scores

array([1.        , 0.86666667, 0.93333333, 1.        , 1.        ,
       0.86666667, 0.86666667])

In [34]:
y_pred = cross_val_predict(model7, X, np.asarray(y).reshape(y.shape[0],), cv=7)
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[48  5]
 [ 2 51]]


In [35]:
model8=RandomForestClassifier(n_estimators=90,criterion="entropy",random_state=0)
scores=cross_val_score(model8,X,np.asarray(y).reshape(y.shape[0],),cv=6)
print("Accuracy is: ",scores.mean(), "+/-",scores.std())

Accuracy is:  0.914488017429194 +/- 0.03003554614152993


In [36]:
y_pred = cross_val_predict(model8, X, np.asarray(y).reshape(y.shape[0],), cv=6)
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[47  6]
 [ 3 50]]


In [37]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=1)
print(X_train.shape)
print(X_test.shape)

(79, 228)
(27, 228)


In [38]:
model8=svm.SVC(kernel="linear",random_state=0).fit(X_train,np.asarray(y_train).reshape(y_train.shape[0],))
model8

SVC(kernel='linear', random_state=0)

In [39]:
train_pred=model8.predict(X_train)
test_pred=model8.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,train_pred))
print("Accuracy on test data: ",accuracy_score(y_test,test_pred))

Accuracy on train data:  1.0
Accuracy on test data:  0.9629629629629629
