In [1]:
# Load the libraries
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/con

In [2]:
# Load the data
import pandas as pd
df=pd.read_csv("bank-full.csv",sep=";")
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

### Prepare the data for the classification model

In [3]:
# Load the libraries for integer encoding.
from sklearn.preprocessing import LabelEncoder

The following code blocks apply integer encoding to all the categorical variables.

In [4]:
from numpy import array
data=df["job"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
job_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(job_code=job_integer_encoder.values)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

   job_code  
0         4  
1         9  
2         2  
3         1  
4        11

In [5]:
import numpy as np
print(np.unique(df["job"]))
print(np.unique(df["job_code"]))

['admin.' 'blue-collar' 'entrepreneur' 'housemaid' 'management' 'retired'
 'self-employed' 'services' 'student' 'technician' 'unemployed' 'unknown']
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
data=df["marital"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
marital_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(marital_code = marital_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

   job_code  marital_code  
0         4             1  
1         9             2  
2         2             1  
3         1             1  
4        11             2

In [7]:
print(np.unique(df["marital"]))
print(np.unique(df["marital_code"]))

['divorced' 'married' 'single']
[0 1 2]


In [8]:
data=df["education"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
education_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(education_code=education_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

   job_code  marital_code  education_code  
0         4             1               2  
1         9             2               1  
2         2             1               1  
3         1             1               3  
4        11             2               3

In [9]:
print(np.unique(df["education"]))
print(np.unique(df["education_code"]))

['primary' 'secondary' 'tertiary' 'unknown']
[0 1 2 3]


In [10]:
data=df["default"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
default_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(default_code=default_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... duration  campaign  pdays  previous  poutcome   y  \
0  unknown    5  ...      261         1     -1         0   unknown  no   
1  unknown    5  ...      151         1     -1         0   unknown  no   
2  unknown    5  ...       76         1     -1         0   unknown  no   
3  unknown    5  ...       92         1     -1         0   unknown  no   
4  unknown    5  ...      198         1     -1         0   unknown  no   

  job_code  marital_code  education_code  default_code  
0        4             1               2             0  
1        9             2               1             0  
2        2             1               1             0  
3        1             1               3             0  
4       11             2               3             0  

[5 rows x 21 columns]

In [11]:
print(np.unique(df["default"]))
print(np.unique(df["default_code"]))

['no' 'yes']
[0 1]


In [12]:
data=df["housing"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
housing_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(housing_code=housing_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... campaign  pdays  previous  poutcome   y job_code  \
0  unknown    5  ...        1     -1         0   unknown  no        4   
1  unknown    5  ...        1     -1         0   unknown  no        9   
2  unknown    5  ...        1     -1         0   unknown  no        2   
3  unknown    5  ...        1     -1         0   unknown  no        1   
4  unknown    5  ...        1     -1         0   unknown  no       11   

  marital_code  education_code  default_code  housing_code  
0            1               2             0             1  
1            2               1             0             1  
2            1               1             0             1  
3            1               3             0             1  
4            2               3             0             0  

[5 rows x 22 columns]

In [13]:
print(np.unique(df["housing"]))
print(np.unique(df["housing_code"]))

['no' 'yes']
[0 1]


In [14]:
data=df["loan"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
loan_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(loan_code=loan_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... pdays  previous  poutcome   y  job_code marital_code  \
0  unknown    5  ...    -1         0   unknown  no         4            1   
1  unknown    5  ...    -1         0   unknown  no         9            2   
2  unknown    5  ...    -1         0   unknown  no         2            1   
3  unknown    5  ...    -1         0   unknown  no         1            1   
4  unknown    5  ...    -1         0   unknown  no        11            2   

  education_code  default_code  housing_code  loan_code  
0              2             0             1          0  
1              1             0             1          0  
2              1             0             1          1  
3              3             0             1          0  
4              3             0             0          0  

[5 rows x 23 columns]

In [15]:
print(np.unique(df["loan"]))
print(np.unique(df["loan_code"]))

['no' 'yes']
[0 1]


In [16]:
data=df["contact"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
contact_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(contact_code=contact_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... previous  poutcome   y  job_code  marital_code  \
0  unknown    5  ...        0   unknown  no         4             1   
1  unknown    5  ...        0   unknown  no         9             2   
2  unknown    5  ...        0   unknown  no         2             1   
3  unknown    5  ...        0   unknown  no         1             1   
4  unknown    5  ...        0   unknown  no        11             2   

  education_code default_code  housing_code  loan_code  contact_code  
0              2            0             1          0             2  
1              1            0             1          0             2  
2              1            0             1          1             2  
3              3            0             1          0             2  
4              3            0             0          0             2  

[5 rows x 24 columns]

In [17]:
print(np.unique(df["contact"]))
print(np.unique(df["contact_code"]))

['cellular' 'telephone' 'unknown']
[0 1 2]


In [18]:
data=df["poutcome"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
poutcome_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(poutcome_code=poutcome_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... poutcome   y  job_code  marital_code  education_code  \
0  unknown    5  ...  unknown  no         4             1               2   
1  unknown    5  ...  unknown  no         9             2               1   
2  unknown    5  ...  unknown  no         2             1               1   
3  unknown    5  ...  unknown  no         1             1               3   
4  unknown    5  ...  unknown  no        11             2               3   

  default_code housing_code  loan_code  contact_code  poutcome_code  
0            0            1          0             2              3  
1            0            1          0             2              3  
2            0            1          1             2              3  
3            0            1          0             2              3  
4            0            0          0             2              3  

[5 rows x 25 columns]

In [19]:
print(np.unique(df["poutcome"]))
print(np.unique(df["poutcome_code"]))

['failure' 'other' 'success' 'unknown']
[0 1 2 3]


In [20]:
data=df["month"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
month_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(month_code=month_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ...   y  job_code  marital_code  education_code  \
0  unknown    5  ...  no         4             1               2   
1  unknown    5  ...  no         9             2               1   
2  unknown    5  ...  no         2             1               1   
3  unknown    5  ...  no         1             1               3   
4  unknown    5  ...  no        11             2               3   

   default_code housing_code loan_code  contact_code  poutcome_code  \
0             0            1         0             2              3   
1             0            1         0             2              3   
2             0            1         1             2              3   
3             0            1         0             2              3   
4             0            0         0             2              3   

   month_code  
0           8  
1           8  
2           8  
3           8  
4           8  

[5 rows x 26 columns]

In [21]:
print(np.unique(df["month"]))
print(np.unique(df["month_code"]))

['apr' 'aug' 'dec' 'feb' 'jan' 'jul' 'jun' 'mar' 'may' 'nov' 'oct' 'sep']
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
data=df["y"]
values=array(data)
label_encoder=LabelEncoder()
integer_encoder=label_encoder.fit_transform(values)
y_integer_encoder=pd.DataFrame(data=integer_encoder)
df=df.assign(outcome_code=y_integer_encoder)
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... job_code  marital_code  education_code  default_code  \
0  unknown    5  ...        4             1               2             0   
1  unknown    5  ...        9             2               1             0   
2  unknown    5  ...        2             1               1             0   
3  unknown    5  ...        1             1               3             0   
4  unknown    5  ...       11             2               3             0   

   housing_code loan_code contact_code  poutcome_code  month_code  \
0             1         0            2              3           8   
1             1         0            2              3           8   
2             1         1            2              3           8   
3             1         0            2              3           8   
4             0         0            2              3           8   

   outcome_code  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 27 columns]

Form a new dataset with only the integer labels and numeric variables.

In [23]:
df=df[["age","balance","day","campaign","previous","job_code","marital_code","education_code","housing_code","loan_code","contact_code","poutcome_code","month_code","outcome_code"]]
df.head()

age  balance  day  campaign  previous  job_code  marital_code  \
0   58     2143    5         1         0         4             1   
1   44       29    5         1         0         9             2   
2   33        2    5         1         0         2             1   
3   47     1506    5         1         0         1             1   
4   33        1    5         1         0        11             2   

   education_code  housing_code  loan_code  contact_code  poutcome_code  \
0               2             1          0             2              3   
1               1             1          0             2              3   
2               1             1          1             2              3   
3               3             1          0             2              3   
4               3             0          0             2              3   

   month_code  outcome_code  
0           8             0  
1           8             0  
2           8             0  
3           8             0  
4           8             0

In [24]:
X=df[["age","balance","day","campaign","previous","job_code","marital_code","education_code","housing_code","loan_code","contact_code","poutcome_code","month_code"]]
X

age  balance  day  campaign  previous  job_code  marital_code  \
0       58     2143    5         1         0         4             1   
1       44       29    5         1         0         9             2   
2       33        2    5         1         0         2             1   
3       47     1506    5         1         0         1             1   
4       33        1    5         1         0        11             2   
...    ...      ...  ...       ...       ...       ...           ...   
45206   51      825   17         3         0         9             1   
45207   71     1729   17         2         0         5             0   
45208   72     5715   17         5         3         5             1   
45209   57      668   17         4         0         1             1   
45210   37     2971   17         2        11         2             1   

       education_code  housing_code  loan_code  contact_code  poutcome_code  \
0                   2             1          0             2              3   
1                   1             1          0             2              3   
2                   1             1          1             2              3   
3                   3             1          0             2              3   
4                   3             0          0             2              3   
...               ...           ...        ...           ...            ...   
45206               2             0          0             0              3   
45207               0             0          0             0              3   
45208               1             0          0             0              2   
45209               1             0          0             1              3   
45210               1             0          0             0              1   

       month_code  
0               8  
1               8  
2               8  
3               8  
4               8  
...           ...  
45206           9  
45207           9  
45208           9  
45209           9  
45210           9  

[45211 rows x 13 columns]

In [25]:
from sklearn import preprocessing
names=X.columns
scaler=preprocessing.StandardScaler()
X=scaler.fit_transform(X)
X=pd.DataFrame(X, columns=names)
X

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


age   balance       day  campaign  previous  job_code  \
0      1.606965  0.256419 -1.298476 -0.569351 -0.251940 -0.103820   
1      0.288529 -0.437895 -1.298476 -0.569351 -0.251940  1.424008   
2     -0.747384 -0.446762 -1.298476 -0.569351 -0.251940 -0.714951   
3      0.571051  0.047205 -1.298476 -0.569351 -0.251940 -1.020516   
4     -0.747384 -0.447091 -1.298476 -0.569351 -0.251940  2.035139   
...         ...       ...       ...       ...       ...       ...   
45206  0.947747 -0.176460  0.143418  0.076230 -0.251940  1.424008   
45207  2.831227  0.120447  0.143418 -0.246560 -0.251940  0.201746   
45208  2.925401  1.429593  0.143418  0.721811  1.050473  0.201746   
45209  1.512791 -0.228024  0.143418  0.399020 -0.251940 -1.020516   
45210 -0.370689  0.528364  0.143418 -0.246560  4.523577 -0.714951   

       marital_code  education_code  housing_code  loan_code  contact_code  \
0         -0.275762        1.036362      0.893915  -0.436803      1.514306   
1          1.368372       -0.300556      0.893915  -0.436803      1.514306   
2         -0.275762       -0.300556      0.893915   2.289359      1.514306   
3         -0.275762        2.373280      0.893915  -0.436803      1.514306   
4          1.368372        2.373280     -1.118674  -0.436803      1.514306   
...             ...             ...           ...        ...           ...   
45206     -0.275762        1.036362     -1.118674  -0.436803     -0.713012   
45207     -1.919895       -1.637474     -1.118674  -0.436803     -0.713012   
45208     -0.275762       -0.300556     -1.118674  -0.436803     -0.713012   
45209     -0.275762       -0.300556     -1.118674  -0.436803      0.400647   
45210     -0.275762       -0.300556     -1.118674  -0.436803     -0.713012   

       poutcome_code  month_code  
0           0.444898    0.823773  
1           0.444898    0.823773  
2           0.444898    0.823773  
3           0.444898    0.823773  
4           0.444898    0.823773  
...              ...         ...  
45206       0.444898    1.156344  
45207       0.444898    1.156344  
45208      -0.566175    1.156344  
45209       0.444898    1.156344  
45210      -1.577248    1.156344  

[45211 rows x 13 columns]

In [26]:
y=df[["outcome_code"]]
y

outcome_code
0                 0
1                 0
2                 0
3                 0
4                 0
...             ...
45206             1
45207             1
45208             1
45209             0
45210             0

[45211 rows x 1 columns]

Split the data into train and test datasets.

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=42)

In [28]:
length=X_test.shape[1]
length

13

In [29]:
from keras.utils import to_categorical
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)
num_classes=y_test.shape[1]
print(num_classes)

2


In [30]:
# define classification model
def classification_model():
    # create model
    model = Sequential()
    model.add(Dense(length, activation='relu', input_shape=(length,)))
    model.add(Dense(300, activation='sigmoid'))
    model.add(Dense(num_classes, activation='softmax'))
    
    
    # compile model
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [31]:
model=classification_model()
model.fit(X_train,y_train,validation_data=(X_test, y_test),epochs=20, verbose=2)
model.evaluate(X_test,y_test,verbose=0)

Train on 31647 samples, validate on 13564 samples
Epoch 1/20
 - 17s - loss: 0.3396 - acc: 0.8790 - val_loss: 0.3349 - val_acc: 0.8822
Epoch 2/20
 - 15s - loss: 0.3232 - acc: 0.8848 - val_loss: 0.3266 - val_acc: 0.8847
Epoch 3/20
 - 16s - loss: 0.3182 - acc: 0.8884 - val_loss: 0.3180 - val_acc: 0.8885
Epoch 4/20
 - 16s - loss: 0.3160 - acc: 0.8900 - val_loss: 0.3160 - val_acc: 0.8891
Epoch 5/20
 - 15s - loss: 0.3142 - acc: 0.8906 - val_loss: 0.3145 - val_acc: 0.8902
Epoch 6/20
 - 16s - loss: 0.3117 - acc: 0.8911 - val_loss: 0.3132 - val_acc: 0.8908
Epoch 7/20
 - 16s - loss: 0.3116 - acc: 0.8911 - val_loss: 0.3139 - val_acc: 0.8914
Epoch 8/20
 - 16s - loss: 0.3112 - acc: 0.8914 - val_loss: 0.3141 - val_acc: 0.8910
Epoch 9/20
 - 15s - loss: 0.3099 - acc: 0.8910 - val_loss: 0.3129 - val_acc: 0.8912
Epoch 10/20
 - 16s - loss: 0.3100 - acc: 0.8919 - val_loss: 0.3145 - val_acc: 0.8915
Epoch 11/20
 - 17s - loss: 0.3088 - acc: 0.8918 - val_loss: 0.3152 - val_acc: 0.8907
Epoch 12/20
 - 16s - los

[0.3111624574633131, 0.8921409613507506]

In [32]:
from sklearn.metrics import roc_auc_score
y_pred=model.predict(X_test)
print("The AUC on the test data is: ",roc_auc_score(y_test,y_pred))
    

The AUC on the test data is:  0.7481627387317884
