In [1]:
pip install -U scikit-learn

     |████████████████████████████████| 6.8MB 23.7MB/s eta 0:00:01
     |████████████████████████████████| 307kB 30.4MB/s eta 0:00:01
  Found existing installation: scikit-learn 0.20.1
    Uninstalling scikit-learn-0.20.1:
      Successfully uninstalled scikit-learn-0.20.1
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_4d48cf73646441e0b238705225f8b4c3.csv"
df=pd.read_csv(url)
df.head()

ID  Recording  Status  Gender  Jitter_rel  Jitter_abs  Jitter_RAP  \
0  CONT-01          1       0       1     0.25546    0.000015    0.001467   
1  CONT-01          2       0       1     0.36964    0.000022    0.001932   
2  CONT-01          3       0       1     0.23514    0.000013    0.001353   
3  CONT-02          1       0       0     0.29320    0.000017    0.001105   
4  CONT-02          2       0       0     0.23075    0.000015    0.001073   

   Jitter_PPQ  Shim_loc  Shim_dB  ...    Delta3    Delta4    Delta5    Delta6  \
0    0.001673  0.030256  0.26313  ...  1.407701  1.417218  1.380352  1.420670   
1    0.002245  0.023146  0.20217  ...  1.331232  1.227338  1.213377  1.352739   
2    0.001546  0.019338  0.16710  ...  1.412304  1.324674  1.276088  1.429634   
3    0.001444  0.024716  0.20892  ...  1.501200  1.534170  1.323993  1.496442   
4    0.001404  0.013119  0.11607  ...  1.508468  1.334511  1.610694  1.685021   

     Delta7    Delta8    Delta9   Delta10   Delta11   Delta12  
0  1.451240  1.440295  1.403678  1.405495  1.416705  1.354610  
1  1.354242  1.365692  1.322870  1.314549  1.318999  1.323508  
2  1.455996  1.368882  1.438053  1.388910  1.305469  1.305402  
3  1.472926  1.643177  1.551286  1.638346  1.604008  1.621456  
4  1.417614  1.574895  1.640088  1.533666  1.297536  1.382023  

[5 rows x 48 columns]

In [2]:
df=df.drop(["ID"],axis=1)
df.shape

(240, 47)

In [3]:
df.isna().any()

Recording     False
Status        False
Gender        False
Jitter_rel    False
Jitter_abs    False
Jitter_RAP    False
Jitter_PPQ    False
Shim_loc      False
Shim_dB       False
Shim_APQ3     False
Shim_APQ5     False
Shi_APQ11     False
HNR05         False
HNR15         False
HNR25         False
HNR35         False
HNR38         False
RPDE          False
DFA           False
PPE           False
GNE           False
MFCC0         False
MFCC1         False
MFCC2         False
MFCC3         False
MFCC4         False
MFCC5         False
MFCC6         False
MFCC7         False
MFCC8         False
MFCC9         False
MFCC10        False
MFCC11        False
MFCC12        False
Delta0        False
Delta1        False
Delta2        False
Delta3        False
Delta4        False
Delta5        False
Delta6        False
Delta7        False
Delta8        False
Delta9        False
Delta10       False
Delta11       False
Delta12       False
dtype: bool

In [4]:
df.groupby("Status").count().T.head()

Status        0    1
Recording   120  120
Gender      120  120
Jitter_rel  120  120
Jitter_abs  120  120
Jitter_RAP  120  120

In [5]:
X=df.drop(["Status"],axis=1)
X.head()

Recording  Gender  Jitter_rel  Jitter_abs  Jitter_RAP  Jitter_PPQ  \
0          1       1     0.25546    0.000015    0.001467    0.001673   
1          2       1     0.36964    0.000022    0.001932    0.002245   
2          3       1     0.23514    0.000013    0.001353    0.001546   
3          1       0     0.29320    0.000017    0.001105    0.001444   
4          2       0     0.23075    0.000015    0.001073    0.001404   

   Shim_loc  Shim_dB  Shim_APQ3  Shim_APQ5  ...    Delta3    Delta4    Delta5  \
0  0.030256  0.26313   0.017463   0.019660  ...  1.407701  1.417218  1.380352   
1  0.023146  0.20217   0.013010   0.014097  ...  1.331232  1.227338  1.213377   
2  0.019338  0.16710   0.011049   0.012683  ...  1.412304  1.324674  1.276088   
3  0.024716  0.20892   0.014525   0.015696  ...  1.501200  1.534170  1.323993   
4  0.013119  0.11607   0.006461   0.008385  ...  1.508468  1.334511  1.610694   

     Delta6    Delta7    Delta8    Delta9   Delta10   Delta11   Delta12  
0  1.420670  1.451240  1.440295  1.403678  1.405495  1.416705  1.354610  
1  1.352739  1.354242  1.365692  1.322870  1.314549  1.318999  1.323508  
2  1.429634  1.455996  1.368882  1.438053  1.388910  1.305469  1.305402  
3  1.496442  1.472926  1.643177  1.551286  1.638346  1.604008  1.621456  
4  1.685021  1.417614  1.574895  1.640088  1.533666  1.297536  1.382023  

[5 rows x 46 columns]

In [6]:
y=df[["Status"]]
y.head()

Status
0       0
1       0
2       0
3       0
4       0

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)
X.head()

Recording    Gender  Jitter_rel  Jitter_abs  Jitter_RAP  Jitter_PPQ  \
0  -1.224745  1.224745   -0.614469   -0.662971   -0.506666   -0.418506   
1   0.000000  1.224745   -0.400910   -0.506000   -0.368597   -0.289864   
2   1.224745  1.224745   -0.652475   -0.695602   -0.540626   -0.447086   
3  -1.224745 -0.816497   -0.543881   -0.602009   -0.614281   -0.470103   
4   0.000000 -0.816497   -0.660686   -0.663414   -0.623759   -0.479112   

   Shim_loc   Shim_dB  Shim_APQ3  Shim_APQ5  ...    Delta3    Delta4  \
0 -0.352789 -0.358691  -0.293390  -0.264977  ...  0.325967  0.322848   
1 -0.659723 -0.655370  -0.617055  -0.652047  ... -0.060705 -0.574647   
2 -0.824112 -0.826047  -0.759589  -0.750432  ...  0.349243 -0.114575   
3 -0.591947 -0.622519  -0.506938  -0.540790  ...  0.798755  0.875640   
4 -1.092582 -1.074398  -1.093096  -1.049512  ...  0.835506 -0.068078   

     Delta5    Delta6    Delta7    Delta8    Delta9   Delta10   Delta11  \
0  0.208432  0.377491  0.517459  0.456646  0.305441  0.351243  0.318174   
1 -0.607871  0.052417  0.062588  0.102947 -0.091342 -0.080073 -0.123891   
2 -0.301290  0.420389  0.539764  0.118074  0.474227  0.272589 -0.185105   
3 -0.067094  0.740090  0.619154  1.418525  1.030224  1.455556  1.165614   
4  1.334520  1.642508  0.359772  1.094794  1.466256  0.959102 -0.220999   

    Delta12  
0  0.040627  
1 -0.108627  
2 -0.195514  
3  1.321177  
4  0.172176  

[5 rows x 46 columns]

In [8]:
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

# feature extraction. We are going to output the selection scores for all features and select the features with the highest scores.
test = SelectKBest(score_func=f_classif, k="all")
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
# summarize scores
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

scores
30  116.056158
14  114.843733
44  114.735126
15  114.540537
25  111.749645
23  107.934553
36  107.596895
38  107.515109
42  103.862007
24  103.226941
13  102.278648
32  102.090842
40   99.089754
34   98.672547
28   95.625729
35   95.535730
31   95.397952
45   94.673494
33   94.579652
29   94.403728
12   93.478815
37   90.953461
11   89.837792
26   89.455281
43   88.901326
27   84.951612
20   81.243879
39   79.508615
41   70.282869
21   29.380522
19   22.679495
8    15.928361
9    14.916892
7    14.504496
6    14.218122
22   12.811006
4    10.310022
10    9.841966
2     8.953146
5     6.894969
18    4.149031
1     2.505263
3     2.250259
16    1.524742
17    0.040428
0     0.000000

In [9]:
#(8, 16, 1, 0)

In [10]:
scores=scores[scores["scores"]>0]
X=X.iloc[:,scores.index]
X.head()

MFCC10     HNR35   Delta11     HNR38     MFCC5     MFCC3    Delta3  \
0  0.101960 -0.149284  0.318174 -0.228541 -0.598428 -0.093842  0.325967   
1  0.116714 -0.011545 -0.123891 -0.071178 -0.426257 -0.753608 -0.060705   
2  0.078448 -0.073271 -0.185105 -0.142394 -0.018092 -0.013827  0.349243   
3  0.701720  0.243730  1.165614  0.158243  1.168629  0.692985  0.798755   
4  1.005771  0.632391 -0.220999  0.555302 -0.369798  1.229621  0.835506   

     Delta5    Delta9     MFCC4  ...     MFCC2  Jitter_RAP  Shi_APQ11  \
0  0.208432  0.305441 -0.327441  ...  0.051423   -0.506666  -0.409597   
1 -0.607871 -0.091342 -0.462302  ... -0.091389   -0.368597  -0.714508   
2 -0.301290  0.474227 -0.068514  ...  0.212736   -0.540626  -0.943162   
3 -0.067094  1.030224  0.978634  ...  1.095069   -0.614281  -0.623892   
4  1.334520  1.466256  0.696630  ...  0.979058   -0.623759  -1.063883   

   Jitter_rel  Jitter_PPQ       PPE    Gender  Jitter_abs      RPDE       DFA  
0   -0.614469   -0.418506 -1.162138  1.224745   -0.662971 -0.917290 -0.174762  
1   -0.400910   -0.289864 -0.855996  1.224745   -0.506000 -0.596505 -0.408005  
2   -0.652475   -0.447086 -1.162634  1.224745   -0.695602 -1.633324 -0.156557  
3   -0.543881   -0.470103 -1.052616 -0.816497   -0.602009 -0.750465  0.158541  
4   -0.660686   -0.479112 -1.030452 -0.816497   -0.663414 -1.350304 -0.134223  

[5 rows x 45 columns]

In [60]:
import numpy as np
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

forest=RandomForestClassifier(n_estimators=250,criterion="entropy",max_depth=4,min_samples_split=3,min_samples_leaf=3,max_features="log2",bootstrap=False,n_jobs=-1,warm_start=True,class_weight="balanced_subsample",ccp_alpha=0.02,random_state=0)
scores=cross_val_score(forest,X,np.asarray(y).reshape(240,),cv=16)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/_forest.py:586: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn('class_weight presets "balanced" or '
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/_forest.py:586: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to prop

In [61]:
print("Accuracy: ",scores.mean())

Accuracy:  0.8083333333333333


In [62]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(forest, X, np.asarray(y).reshape(240,), cv=16)
AUC = roc_auc_score(y, y_pred)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/_forest.py:586: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn('class_weight presets "balanced" or '
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/_forest.py:586: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to prop

In [63]:
print("AUC for the Random Forest model: ",AUC)

AUC for the Random Forest model:  0.8083333333333333


In [64]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[100  20]
 [ 26  94]]


In [66]:
print("Sensitivity: ",94/120)
print("Specificity: ",100/120)

Sensitivity:  0.7833333333333333
Specificity:  0.8333333333333334


In [99]:
from sklearn.ensemble import GradientBoostingClassifier
gradient=GradientBoostingClassifier(loss="deviance",learning_rate=0.03,n_estimators=220,subsample=0.5,criterion="friedman_mse",min_samples_split=2,min_samples_leaf=3,max_depth=3,max_features="sqrt",ccp_alpha=0.01,random_state=0)
scores=cross_val_score(gradient,X,np.asarray(y).reshape(240,),cv=16)
print("Accuracy: ",scores.mean())

Accuracy:  0.8083333333333333


In [100]:
y_pred = cross_val_predict(gradient, X, np.asarray(y).reshape(240,), cv=16)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Gradient Boosting model: ",AUC)

AUC for the Gradient Boosting model:  0.8083333333333331


In [101]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[99 21]
 [25 95]]


In [102]:
print("Sensitivity: ",95/120)
print("Specificity: ",99/120)

Sensitivity:  0.7916666666666666
Specificity:  0.825


In [133]:
from sklearn import svm
import numpy as np

svm=svm.SVC(C=0.015,kernel="linear",degree=2,gamma="scale",cache_size=150,
            decision_function_shape="ovr",probability=True,random_state=0)
scores=cross_val_score(svm,X,np.asarray(y).reshape(240,),cv=16)
print("Accuracy: ",scores.mean())

Accuracy:  0.8333333333333334


In [134]:
y_pred = cross_val_predict(svm, X, np.asarray(y).reshape(240,), cv=16)
AUC = roc_auc_score(y, y_pred)
print("AUC for the SVM model: ",AUC)

AUC for the SVM model:  0.8333333333333334


In [135]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[ 98  22]
 [ 18 102]]


In [136]:
print("Sensitivity: ",102/120)
print("Specificity: ",98/120)

Sensitivity:  0.85
Specificity:  0.8166666666666667


In [170]:
y_pred =pd.DataFrame((cross_val_predict(svm, X, np.asarray(y).reshape(240,), cv=16,method="predict_proba"))).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

pred_0    pred_1
0  0.576072  0.423928
1  0.483195  0.516805
2  0.523986  0.476014
3  0.830452  0.169548
4  0.784913  0.215087

In [141]:
y_probs1=y_pred[["pred_1"]]

In [142]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [143]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [144]:
from sklearn.metrics import f1_score
scores=[f1_score(y, to_labels(y_probs1,t)) for t in thresholds]

In [145]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.491, 0.8326530612244897)


In [161]:
len(y_probs1[y_probs1["pred_1"]>=0.491])

125

In [171]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.491),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.491),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.491),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.491),0,y_pred.pred_1)

In [176]:
y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)
#y_pred["pred_1"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_1)

In [173]:
y_pred.head()

pred_0  pred_1
0     1.0     0.0
1     0.0     1.0
2     1.0     0.0
3     1.0     0.0
4     1.0     0.0

In [177]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  115


In [178]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  125


In [179]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(handle_unknown="ignore")
y_true=np.asarray(y).reshape(-1,1)
y_true=pd.DataFrame(enc.fit_transform(y_true).toarray()).rename(columns={0:"y_0",1:"y_1"})
y_true.head()

y_0  y_1
0  1.0  0.0
1  1.0  0.0
2  1.0  0.0
3  1.0  0.0
4  1.0  0.0

In [180]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 199)

In [169]:
print("Accuracy: ",199/240)

Accuracy:  0.8291666666666667


In [90]:
from sklearn.naive_bayes import GaussianNB
NB=GaussianNB()
scores=cross_val_score(NB,X,np.asarray(y).reshape(240,),cv=24)
print("Accuracy: ",scores.mean())

Accuracy:  0.8375


In [93]:
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(NB, X, np.asarray(y).reshape(240,), cv=24)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Naive Bayes model: ",AUC)

AUC for the Naive Bayes model:  0.8375000000000001


In [94]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[103  17]
 [ 22  98]]


In [95]:
print("Sensitivity: ",98/120)
print("Specificity: ", 103/120)

Sensitivity:  0.8166666666666667
Specificity:  0.8583333333333333


In [110]:
y_pred =pd.DataFrame((cross_val_predict(NB, X,np.asarray(y).reshape(240,), cv=24,method="predict_proba"))).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

pred_0        pred_1
0  0.999989  1.110727e-05
1  0.793542  2.064577e-01
2  0.999446  5.536328e-04
3  1.000000  8.266246e-19
4  1.000000  9.614880e-16

In [111]:
y_probs1=y_pred[["pred_1"]]

In [112]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [113]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [114]:

from sklearn.metrics import f1_score
scores=[f1_score(y, to_labels(y_probs1,t)) for t in thresholds]

In [115]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.427, 0.8340425531914893)


In [116]:
len(y_probs1[y_probs1["pred_1"]>=0.427])

115

In [117]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.427),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.427),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.427),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.427),0,y_pred.pred_1)

In [118]:
y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)
#y_pred["pred_1"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_1)

In [119]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  125


In [120]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  115


In [238]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 201)

Total number of correct predictions is 201.

In [239]:
print("Accuracy after adjusting the threshold: ",201/240)

Accuracy after adjusting the threshold:  0.8375


In [240]:
print("New confusion matrix: \n",np.array([[103,17],[22,98]]))

New confusion matrix: 
 [[103  17]
 [ 22  98]]


In [241]:
print("Sensitivity: ",98/120)
print("Specificity: ",103/120)

Sensitivity:  0.8166666666666667
Specificity:  0.8583333333333333


No improvements.

In [351]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=6,weights="uniform",algorithm="brute",leaf_size=35,p=1,n_jobs=-1)
scores=cross_val_score(KNN,X,np.asarray(y).reshape(240,),cv=10)
print("Accuracy: ",scores.mean())

Accuracy:  0.7666666666666667


In [384]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(penalty="l2",C=0.05,class_weight="liblinear",solver="lbfgs",max_iter=100,multi_class="auto",n_jobs=-1,warm_start=False,random_state=0)
scores=cross_val_score(LR,X,np.asarray(y).reshape(240,),cv=12)
print("Accuracy: ",scores.mean())

Accuracy:  0.8291666666666666


In [385]:
y_pred = cross_val_predict(LR, X, np.asarray(y).reshape(240,), cv=12)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Naive Bayes model: ",AUC)

AUC for the Naive Bayes model:  0.8291666666666666


In [386]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[ 99  21]
 [ 20 100]]


In [387]:
print("Sensitivity: ",100/120)
print("Specificity: ",99/120)

Sensitivity:  0.8333333333333334
Specificity:  0.825


In [388]:
y_pred =pd.DataFrame((cross_val_predict(LR, X, y, cv=12,method="predict_proba"))).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


pred_0    pred_1
0  0.613858  0.386142
1  0.463046  0.536954
2  0.552706  0.447294
3  0.864809  0.135191
4  0.861123  0.138877

In [389]:
y_probs1=y_pred[["pred_1"]]

In [390]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [391]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [392]:
from sklearn.metrics import f1_score
scores=[f1_score(y, to_labels(y_probs1,t)) for t in thresholds]

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [393]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.498, 0.8298755186721992)


In [394]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.498),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.498),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.498),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.498),0,y_pred.pred_1)

In [395]:
y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_1)

In [396]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  119


In [397]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  121


In [398]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 199)

We maxed out the Logistic Regression model already.

In [20]:
import keras
from keras import metrics
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [13]:
from sklearn.preprocessing import OneHotEncoder
ienc=OneHotEncoder(handle_unknown="ignore")
y=ienc.fit_transform(y)
y=pd.DataFrame(y.toarray())
y.head()

0    1
0  1.0  0.0
1  1.0  0.0
2  1.0  0.0
3  1.0  0.0
4  1.0  0.0

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(X_train.shape)
print(X_test.shape)

(168, 45)
(72, 45)


In [41]:
length=X_train.shape[1]
num_classes=y_test.shape[1]
print(length)
print(num_classes)

45
2


In [42]:
def classification_model():
    model = Sequential()
    model.add(Dense(length, activation='relu', input_shape=(length,)))
    model.add(Dense(65, activation='relu'))
    model.add(Dropout(0.4))
    model.add(Dense(65,activation="relu"))
    model.add(Dropout(0.4))
    model.add(Dense(65,activation="relu"))
    model.add(Dropout(0.45))
    model.add(Dense(65,activation="relu"))
    model.add(Dropout(0.45))
    model.add(Dense(num_classes, activation='softmax'))
    opt=Adam(lr=0.003)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [43]:
model=classification_model()
model.fit(X_train,y_train,validation_data=(X_test, y_test),epochs=15, verbose=2)
model.evaluate(X_test,y_test,verbose=0)

Train on 168 samples, validate on 72 samples
Epoch 1/15
 - 20s - loss: 0.6867 - acc: 0.5417 - val_loss: 0.5884 - val_acc: 0.7639
Epoch 2/15
 - 0s - loss: 0.5921 - acc: 0.6845 - val_loss: 0.4920 - val_acc: 0.8056
Epoch 3/15
 - 0s - loss: 0.5483 - acc: 0.7202 - val_loss: 0.4709 - val_acc: 0.8472
Epoch 4/15
 - 0s - loss: 0.5151 - acc: 0.7857 - val_loss: 0.4973 - val_acc: 0.8333
Epoch 5/15
 - 0s - loss: 0.5374 - acc: 0.7917 - val_loss: 0.4769 - val_acc: 0.7917
Epoch 6/15
 - 0s - loss: 0.4421 - acc: 0.8274 - val_loss: 0.4498 - val_acc: 0.8056
Epoch 7/15
 - 0s - loss: 0.4392 - acc: 0.8036 - val_loss: 0.4336 - val_acc: 0.8194
Epoch 8/15
 - 0s - loss: 0.4854 - acc: 0.8274 - val_loss: 0.4235 - val_acc: 0.8333
Epoch 9/15
 - 0s - loss: 0.4984 - acc: 0.8750 - val_loss: 0.3996 - val_acc: 0.8333
Epoch 10/15
 - 0s - loss: 0.4001 - acc: 0.8571 - val_loss: 0.3870 - val_acc: 0.8889
Epoch 11/15
 - 0s - loss: 0.4287 - acc: 0.8333 - val_loss: 0.3881 - val_acc: 0.8472
Epoch 12/15
 - 0s - loss: 0.3654 - acc:

[0.39311499065823025, 0.9027777777777778]

In [60]:
y_pred=pd.DataFrame(model.predict(X_test)).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

pred_0    pred_1
0  0.133888  0.866112
1  0.991158  0.008842
2  0.996860  0.003140
3  0.954793  0.045207
4  0.928796  0.071204

In [61]:
y_probs1=y_pred[["pred_1"]]

In [62]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [63]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [64]:
y_status=pd.DataFrame(ienc.inverse_transform(y_test)).rename(columns={0:"status"})
y_status.head()

status
0       0
1       0
2       0
3       0
4       0

In [65]:
from sklearn.metrics import f1_score
scores=[f1_score(y_status, to_labels(y_probs1,t)) for t in thresholds]

In [66]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.41400000000000003, 0.918918918918919)


In [67]:
len(y_probs1[y_probs1["pred_1"]>=0.414])

37

In [68]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.414),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.414),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.414),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.414),0,y_pred.pred_1)

In [71]:
y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)
#y_pred["pred_1"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_1)

In [72]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  35


In [70]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  37


In [80]:
y_true=pd.DataFrame(ienc.inverse_transform(y_test))
y_true.head()

0
0  0
1  0
2  0
3  0
4  0

In [81]:
y_pred=pd.DataFrame(ienc.inverse_transform(y_pred))
y_pred.head()

0
0  1
1  0
2  0
3  0
4  0

In [84]:
from sklearn.metrics import accuracy_score
print("Accuracy on test data after adjusting the threshold: ",accuracy_score(y_true,y_pred))

Accuracy on test data after adjusting the threshold:  0.9166666666666666


In [85]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix after adjusting the threshold: \n",confusion_matrix(y_true,y_pred))

Confusion matrix after adjusting the threshold: 
 [[32  3]
 [ 3 34]]


In [86]:
print("Sensitivity: ",34/37)
print("Specificity: ",32/35)

Sensitivity:  0.918918918918919
Specificity:  0.9142857142857143


In [87]:
from sklearn.metrics import roc_auc_score
print("AUC on test data after adjusting the threshold, ",roc_auc_score(y_true,y_pred))

AUC on test data after adjusting the threshold,  0.9166023166023165
