In [1]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_4d48cf73646441e0b238705225f8b4c3.csv"
df=pd.read_csv(url)
df.head()

ID  Recording  Status  Gender  Jitter_rel  Jitter_abs  Jitter_RAP  \
0  CONT-01          1       0       1     0.25546    0.000015    0.001467   
1  CONT-01          2       0       1     0.36964    0.000022    0.001932   
2  CONT-01          3       0       1     0.23514    0.000013    0.001353   
3  CONT-02          1       0       0     0.29320    0.000017    0.001105   
4  CONT-02          2       0       0     0.23075    0.000015    0.001073   

   Jitter_PPQ  Shim_loc  Shim_dB  ...    Delta3    Delta4    Delta5    Delta6  \
0    0.001673  0.030256  0.26313  ...  1.407701  1.417218  1.380352  1.420670   
1    0.002245  0.023146  0.20217  ...  1.331232  1.227338  1.213377  1.352739   
2    0.001546  0.019338  0.16710  ...  1.412304  1.324674  1.276088  1.429634   
3    0.001444  0.024716  0.20892  ...  1.501200  1.534170  1.323993  1.496442   
4    0.001404  0.013119  0.11607  ...  1.508468  1.334511  1.610694  1.685021   

     Delta7    Delta8    Delta9   Delta10   Delta11   Delta12  
0  1.451240  1.440295  1.403678  1.405495  1.416705  1.354610  
1  1.354242  1.365692  1.322870  1.314549  1.318999  1.323508  
2  1.455996  1.368882  1.438053  1.388910  1.305469  1.305402  
3  1.472926  1.643177  1.551286  1.638346  1.604008  1.621456  
4  1.417614  1.574895  1.640088  1.533666  1.297536  1.382023  

[5 rows x 48 columns]

In [2]:
df=df.drop(["ID"],axis=1)
df.shape

(240, 47)

In [3]:
df.isna().any()

Recording     False
Status        False
Gender        False
Jitter_rel    False
Jitter_abs    False
Jitter_RAP    False
Jitter_PPQ    False
Shim_loc      False
Shim_dB       False
Shim_APQ3     False
Shim_APQ5     False
Shi_APQ11     False
HNR05         False
HNR15         False
HNR25         False
HNR35         False
HNR38         False
RPDE          False
DFA           False
PPE           False
GNE           False
MFCC0         False
MFCC1         False
MFCC2         False
MFCC3         False
MFCC4         False
MFCC5         False
MFCC6         False
MFCC7         False
MFCC8         False
MFCC9         False
MFCC10        False
MFCC11        False
MFCC12        False
Delta0        False
Delta1        False
Delta2        False
Delta3        False
Delta4        False
Delta5        False
Delta6        False
Delta7        False
Delta8        False
Delta9        False
Delta10       False
Delta11       False
Delta12       False
dtype: bool

In [4]:
df.groupby("Status").count().T.head()

Status        0    1
Recording   120  120
Gender      120  120
Jitter_rel  120  120
Jitter_abs  120  120
Jitter_RAP  120  120

In [5]:
X=df.drop(["Status"],axis=1)
X.head()

Recording  Gender  Jitter_rel  Jitter_abs  Jitter_RAP  Jitter_PPQ  \
0          1       1     0.25546    0.000015    0.001467    0.001673   
1          2       1     0.36964    0.000022    0.001932    0.002245   
2          3       1     0.23514    0.000013    0.001353    0.001546   
3          1       0     0.29320    0.000017    0.001105    0.001444   
4          2       0     0.23075    0.000015    0.001073    0.001404   

   Shim_loc  Shim_dB  Shim_APQ3  Shim_APQ5  ...    Delta3    Delta4    Delta5  \
0  0.030256  0.26313   0.017463   0.019660  ...  1.407701  1.417218  1.380352   
1  0.023146  0.20217   0.013010   0.014097  ...  1.331232  1.227338  1.213377   
2  0.019338  0.16710   0.011049   0.012683  ...  1.412304  1.324674  1.276088   
3  0.024716  0.20892   0.014525   0.015696  ...  1.501200  1.534170  1.323993   
4  0.013119  0.11607   0.006461   0.008385  ...  1.508468  1.334511  1.610694   

     Delta6    Delta7    Delta8    Delta9   Delta10   Delta11   Delta12  
0  1.420670  1.451240  1.440295  1.403678  1.405495  1.416705  1.354610  
1  1.352739  1.354242  1.365692  1.322870  1.314549  1.318999  1.323508  
2  1.429634  1.455996  1.368882  1.438053  1.388910  1.305469  1.305402  
3  1.496442  1.472926  1.643177  1.551286  1.638346  1.604008  1.621456  
4  1.685021  1.417614  1.574895  1.640088  1.533666  1.297536  1.382023  

[5 rows x 46 columns]

In [6]:
y=df[["Status"]]
y.head()

Status
0       0
1       0
2       0
3       0
4       0

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)
X.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


Recording    Gender  Jitter_rel  Jitter_abs  Jitter_RAP  Jitter_PPQ  \
0  -1.224745  1.224745   -0.614469   -0.662971   -0.506666   -0.418506   
1   0.000000  1.224745   -0.400910   -0.506000   -0.368597   -0.289864   
2   1.224745  1.224745   -0.652475   -0.695602   -0.540626   -0.447086   
3  -1.224745 -0.816497   -0.543881   -0.602009   -0.614281   -0.470103   
4   0.000000 -0.816497   -0.660686   -0.663414   -0.623759   -0.479112   

   Shim_loc   Shim_dB  Shim_APQ3  Shim_APQ5  ...    Delta3    Delta4  \
0 -0.352789 -0.358691  -0.293390  -0.264977  ...  0.325967  0.322848   
1 -0.659723 -0.655370  -0.617055  -0.652047  ... -0.060705 -0.574647   
2 -0.824112 -0.826047  -0.759589  -0.750432  ...  0.349243 -0.114575   
3 -0.591947 -0.622519  -0.506938  -0.540790  ...  0.798755  0.875640   
4 -1.092582 -1.074398  -1.093096  -1.049512  ...  0.835506 -0.068078   

     Delta5    Delta6    Delta7    Delta8    Delta9   Delta10   Delta11  \
0  0.208432  0.377491  0.517459  0.456646  0.305441  0.351243  0.318174   
1 -0.607871  0.052417  0.062588  0.102947 -0.091342 -0.080073 -0.123891   
2 -0.301290  0.420389  0.539764  0.118074  0.474227  0.272589 -0.185105   
3 -0.067094  0.740090  0.619154  1.418525  1.030224  1.455556  1.165614   
4  1.334520  1.642508  0.359772  1.094794  1.466256  0.959102 -0.220999   

    Delta12  
0  0.040627  
1 -0.108627  
2 -0.195514  
3  1.321177  
4  0.172176  

[5 rows x 46 columns]

In [21]:
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif

# feature extraction. We are going to output the selection scores for all features and select the features with the highest scores.
test = SelectKBest(score_func=mutual_info_classif, k="all")
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
# summarize scores
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

scores
14  0.231574
15  0.228834
12  0.213959
30  0.212406
38  0.210662
33  0.210092
36  0.200591
25  0.198324
27  0.194830
40  0.193466
37  0.191792
32  0.191604
11  0.189706
44  0.188060
13  0.185768
34  0.185727
45  0.184346
23  0.182093
24  0.178999
29  0.177869
20  0.176387
28  0.175857
42  0.175372
31  0.166366
43  0.164078
35  0.159502
26  0.151493
41  0.122303
39  0.118957
22  0.103071
21  0.094541
18  0.079365
19  0.077980
17  0.073682
10  0.070614
5   0.051395
9   0.039979
7   0.032505
4   0.028722
2   0.017045
3   0.008447
6   0.007504
1   0.004691
8   0.000000
16  0.000000
0   0.000000

In [22]:
#(8, 16, 1, 0)

In [23]:
scores=scores[scores["scores"]>0]
X=X.iloc[:,scores.index]
X.head()

HNR35     HNR38     HNR15    MFCC10    Delta5    Delta0    Delta3  \
0 -0.149284 -0.228541 -0.188492  0.101960  0.208432  0.265783  0.325967   
1 -0.011545 -0.071178 -0.065367  0.116714 -0.607871 -0.164784 -0.060705   
2 -0.073271 -0.142394 -0.116511  0.078448 -0.301290 -0.117478  0.349243   
3  0.243730  0.158243  0.320979  0.701720 -0.067094  0.183503  0.798755   
4  0.632391  0.555302  0.725034  1.005771  1.334520 -0.390955  0.835506   

      MFCC5     MFCC7    Delta7  ...       DFA  Shi_APQ11  Jitter_PPQ  \
0 -0.598428 -0.291353  0.517459  ... -0.174762  -0.409597   -0.418506   
1 -0.426257 -0.173321  0.062588  ... -0.408005  -0.714508   -0.289864   
2 -0.018092  0.044825  0.539764  ... -0.156557  -0.943162   -0.447086   
3  1.168629  1.415977  0.619154  ...  0.158541  -0.623892   -0.470103   
4 -0.369798  0.521166  0.359772  ... -0.134223  -1.063883   -0.479112   

   Shim_APQ5   Shim_dB  Jitter_RAP  Jitter_rel  Jitter_abs  Shim_loc    Gender  
0  -0.264977 -0.358691   -0.506666   -0.614469   -0.662971 -0.352789  1.224745  
1  -0.652047 -0.655370   -0.368597   -0.400910   -0.506000 -0.659723  1.224745  
2  -0.750432 -0.826047   -0.540626   -0.652475   -0.695602 -0.824112  1.224745  
3  -0.540790 -0.622519   -0.614281   -0.543881   -0.602009 -0.591947 -0.816497  
4  -1.049512 -1.074398   -0.623759   -0.660686   -0.663414 -1.092582 -0.816497  

[5 rows x 43 columns]

In [24]:
import numpy as np
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

forest=RandomForestClassifier(n_estimators=270,criterion="entropy",max_depth=4,min_samples_split=2,min_samples_leaf=3,max_features="log2",bootstrap=False,n_jobs=-1,warm_start=True,class_weight="balanced",random_state=0)
scores=cross_val_score(forest,X,np.asarray(y).reshape(240,),cv=16)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/forest.py:502: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn('class_weight presets "balanced" or "balanced_subsample" are '
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/forest.py:502: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight("balanced", classes, y). In place of y you can use a large enough sample of the full traini

In [25]:
print("Accuracy: ",scores.mean())

Accuracy:  0.7935267857142858


In [26]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(forest, X, np.asarray(y).reshape(240,), cv=16)
AUC = roc_auc_score(y, y_pred)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/forest.py:502: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn('class_weight presets "balanced" or "balanced_subsample" are '
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/ensemble/forest.py:502: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight("balanced", classes, y). In place of y you can use a large enough sample of the full traini

In [27]:
print("AUC for the Random Forest model: ",AUC)

AUC for the Random Forest model:  0.7875000000000001


In [28]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[97 23]
 [28 92]]


In [29]:
print("Sensitivity: ",92/120)
print("Specificity: ",97/120)

Sensitivity:  0.7666666666666667
Specificity:  0.8083333333333333


In [97]:
from sklearn.ensemble import GradientBoostingClassifier
gradient=GradientBoostingClassifier(loss="exponential",learning_rate=0.03,n_estimators=200,subsample=0.5,criterion="mae",min_samples_split=4,min_samples_leaf=2,max_depth=5,max_features="sqrt",random_state=0)
scores=cross_val_score(gradient,X,np.asarray(y).reshape(240,),cv=16)
print("Accuracy: ",scores.mean())

Accuracy:  0.7885044642857143


In [98]:
y_pred = cross_val_predict(gradient, X, np.asarray(y).reshape(240,), cv=16)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Gradient Boosting model: ",AUC)

AUC for the Gradient Boosting model:  0.7833333333333333


In [99]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[97 23]
 [29 91]]


In [101]:
print("Sensitivity: ",91/120)
print("Specificity: ",97/120)

Sensitivity:  0.7583333333333333
Specificity:  0.8083333333333333


In [30]:
from sklearn import svm
import numpy as np

svm=svm.SVC(C=0.01,kernel="linear",degree=3,gamma="auto",cache_size=150,
            decision_function_shape="ovo",probability=True,random_state=0)
scores=cross_val_score(svm,X,np.asarray(y).reshape(240,),cv=16)
print("Accuracy: ",scores.mean())

Accuracy:  0.8303571428571428


In [31]:
y_pred = cross_val_predict(svm, X, np.asarray(y).reshape(240,), cv=16)
AUC = roc_auc_score(y, y_pred)
print("AUC for the SVM model: ",AUC)

AUC for the SVM model:  0.8250000000000002


In [32]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[ 97  23]
 [ 19 101]]


In [33]:
print("Sensitivity: ",101/120)
print("Specificity: ",97/120)

Sensitivity:  0.8416666666666667
Specificity:  0.8083333333333333


In [34]:
y_pred =pd.DataFrame((cross_val_predict(svm, X, y, cv=16,method="predict_proba"))).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


pred_0    pred_1
0  0.576083  0.423917
1  0.469816  0.530184
2  0.556887  0.443113
3  0.816675  0.183325
4  0.804300  0.195700

In [35]:
y_probs1=y_pred[["pred_1"]]

In [36]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [37]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [38]:
from sklearn.metrics import f1_score
scores=[f1_score(y, to_labels(y_probs1,t)) for t in thresholds]

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyte

In [39]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.47700000000000004, 0.83739837398374)


In [40]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.477),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.477),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.477),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.477),0,y_pred.pred_1)

In [41]:
y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_1)

In [42]:
y_pred.head()

pred_0  pred_1
0     1.0     0.0
1     0.0     1.0
2     1.0     0.0
3     1.0     0.0
4     1.0     0.0

In [43]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  114


In [44]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  126


In [45]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(handle_unknown="ignore")
y_true=np.asarray(y).reshape(-1,1)
y_true=pd.DataFrame(enc.fit_transform(y_true).toarray()).rename(columns={0:"y_0",1:"y_1"})
y_true.head()

y_0  y_1
0  1.0  0.0
1  1.0  0.0
2  1.0  0.0
3  1.0  0.0
4  1.0  0.0

In [46]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 200)

In [47]:
print("Accuracy: ",200/240)

Accuracy:  0.8333333333333334


After adjusting the threshold, the SVM model predicted:
- (1) 117 negative cases.
- (2) 123 positive cases
- (3) Total number correct prediction is 195.

The new confusion matrix is therefore:

In [48]:
print("New confusion matrix :\n", np.array([[97,23],[17,103]]))

New confusion matrix :
 [[ 97  23]
 [ 17 103]]


True positive increased by 1, at the cost of increasing false positive by 1 as well.

In [49]:
print("Sensitivity: ",103/120)
print("Specificity: ",97/120)

Sensitivity:  0.8583333333333333
Specificity:  0.8083333333333333


In [50]:
from sklearn.naive_bayes import GaussianNB
NB=GaussianNB()
scores=cross_val_score(NB,X,np.asarray(y).reshape(240,),cv=12)
print("Accuracy: ",scores.mean())

Accuracy:  0.8291666666666666


In [51]:
y_pred = cross_val_predict(NB, X, np.asarray(y).reshape(240,), cv=12)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Naive Bayes model: ",AUC)

AUC for the Naive Bayes model:  0.8291666666666667


In [52]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[101  19]
 [ 22  98]]


In [53]:
print("Sensitivity: ",98/120)
print("Specificity: ", 101/120)

Sensitivity:  0.8166666666666667
Specificity:  0.8416666666666667


In [54]:
y_pred =pd.DataFrame((cross_val_predict(NB, X, y, cv=12,method="predict_proba"))).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


pred_0        pred_1
0  0.999982  1.772145e-05
1  0.558069  4.419309e-01
2  0.999274  7.263820e-04
3  1.000000  1.221785e-20
4  1.000000  2.617304e-17

In [55]:
y_probs1=y_pred[["pred_1"]]

In [56]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [57]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [58]:

from sklearn.metrics import f1_score
scores=[f1_score(y, to_labels(y_probs1,t)) for t in thresholds]

In [59]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.442, 0.8270042194092827)


In [60]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.442),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.442),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.442),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.442),0,y_pred.pred_1)

In [61]:
y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_1)

In [62]:
y_pred.head()

pred_0  pred_1
0     1.0     0.0
1     1.0     0.0
2     1.0     0.0
3     1.0     0.0
4     1.0     0.0

In [63]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  123


In [64]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  117


In [65]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 199)

Total number of correct predictions is 199.

In [331]:
print("Accuracy after adjusting the threshold: ",199/240)

Accuracy after adjusting the threshold:  0.8291666666666667


In [334]:
print("New confusion matrix: \n",np.array([[101,19],[22,98]]))

New confusion matrix: 
 [[101  19]
 [ 22  98]]


In [66]:
print("Sensitivity: ",98/120)
print("Specificity: ",101/120)

Sensitivity:  0.8166666666666667
Specificity:  0.8416666666666667


No improvements.

In [351]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=6,weights="uniform",algorithm="brute",leaf_size=35,p=1,n_jobs=-1)
scores=cross_val_score(KNN,X,np.asarray(y).reshape(240,),cv=10)
print("Accuracy: ",scores.mean())

Accuracy:  0.7666666666666667


In [384]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(penalty="l2",C=0.05,class_weight="liblinear",solver="lbfgs",max_iter=100,multi_class="auto",n_jobs=-1,warm_start=False,random_state=0)
scores=cross_val_score(LR,X,np.asarray(y).reshape(240,),cv=12)
print("Accuracy: ",scores.mean())

Accuracy:  0.8291666666666666


In [385]:
y_pred = cross_val_predict(LR, X, np.asarray(y).reshape(240,), cv=12)
AUC = roc_auc_score(y, y_pred)
print("AUC for the Naive Bayes model: ",AUC)

AUC for the Naive Bayes model:  0.8291666666666666


In [386]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[ 99  21]
 [ 20 100]]


In [387]:
print("Sensitivity: ",100/120)
print("Specificity: ",99/120)

Sensitivity:  0.8333333333333334
Specificity:  0.825


In [388]:
y_pred =pd.DataFrame((cross_val_predict(LR, X, y, cv=12,method="predict_proba"))).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


pred_0    pred_1
0  0.613858  0.386142
1  0.463046  0.536954
2  0.552706  0.447294
3  0.864809  0.135191
4  0.861123  0.138877

In [389]:
y_probs1=y_pred[["pred_1"]]

In [390]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [391]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [392]:
from sklearn.metrics import f1_score
scores=[f1_score(y, to_labels(y_probs1,t)) for t in thresholds]

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [393]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.498, 0.8298755186721992)


In [394]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.498),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.498),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.498),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.498),0,y_pred.pred_1)

In [395]:
y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_1)

In [396]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  119


In [397]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  121


In [398]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 199)

We maxed out the Logistic Regression model already.

In [68]:
import keras
from keras import metrics
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.layers import Dropout

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(192, 43)
(48, 43)


In [70]:
from sklearn.preprocessing import OneHotEncoder
ienc=OneHotEncoder(handle_unknown="ignore")
y_train=ienc.fit_transform(y_train)
y_train=pd.DataFrame(y_train.toarray())
y_train.head()

0    1
0  0.0  1.0
1  1.0  0.0
2  0.0  1.0
3  0.0  1.0
4  0.0  1.0

In [71]:
y_test=ienc.fit_transform(y_test)
y_test=pd.DataFrame(y_test.toarray())
y_test.head()

0    1
0  1.0  0.0
1  1.0  0.0
2  1.0  0.0
3  1.0  0.0
4  1.0  0.0

In [72]:
length=X_train.shape[1]
num_classes=y_test.shape[1]
print(length)
print(num_classes)

43
2


In [140]:
def classification_model():
    model = Sequential()
    model.add(Dense(length, activation='relu', input_shape=(length,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dropout(0.4))
    model.add(Dense(50,activation="relu"))
    model.add(Dropout(0.4))
    model.add(Dense(50,activation="relu"))
    model.add(Dropout(0.45))
    model.add(Dense(50,activation="relu"))
    model.add(Dropout(0.45))
    model.add(Dense(num_classes, activation='softmax'))
    opt=Adam(lr=0.003)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [143]:
model=classification_model()
model.fit(X_train,y_train,validation_data=(X_test, y_test),epochs=16, verbose=2)
model.evaluate(X_test,y_test,verbose=0)

Train on 192 samples, validate on 48 samples
Epoch 1/16
 - 4s - loss: 0.7336 - acc: 0.5000 - val_loss: 0.6169 - val_acc: 0.8125
Epoch 2/16
 - 0s - loss: 0.6389 - acc: 0.5729 - val_loss: 0.5369 - val_acc: 0.7917
Epoch 3/16
 - 0s - loss: 0.5940 - acc: 0.6719 - val_loss: 0.4752 - val_acc: 0.7917
Epoch 4/16
 - 0s - loss: 0.5699 - acc: 0.7448 - val_loss: 0.4673 - val_acc: 0.7708
Epoch 5/16
 - 0s - loss: 0.4925 - acc: 0.8073 - val_loss: 0.4580 - val_acc: 0.7708
Epoch 6/16
 - 0s - loss: 0.4692 - acc: 0.8021 - val_loss: 0.4480 - val_acc: 0.7917
Epoch 7/16
 - 0s - loss: 0.4857 - acc: 0.8333 - val_loss: 0.4319 - val_acc: 0.7917
Epoch 8/16
 - 0s - loss: 0.4539 - acc: 0.8177 - val_loss: 0.4439 - val_acc: 0.7917
Epoch 9/16
 - 0s - loss: 0.4383 - acc: 0.8385 - val_loss: 0.4494 - val_acc: 0.8125
Epoch 10/16
 - 0s - loss: 0.3912 - acc: 0.8750 - val_loss: 0.4214 - val_acc: 0.8125
Epoch 11/16
 - 0s - loss: 0.4178 - acc: 0.8438 - val_loss: 0.4274 - val_acc: 0.8333
Epoch 12/16
 - 0s - loss: 0.3354 - acc: 

[0.4325363834698995, 0.8541666666666666]

In [206]:
y_pred=pd.DataFrame(model.predict(X_test)).rename(columns={0:"pred_0",1:"pred_1"})
y_pred.head()

pred_0    pred_1
0  0.380194  0.619806
1  0.995119  0.004881
2  0.998148  0.001852
3  0.941024  0.058976
4  0.920963  0.079037

In [145]:
len(y_pred)

48

In [146]:
y_probs1=y_pred[["pred_1"]]

In [147]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [148]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [149]:
y_status=pd.DataFrame(ienc.inverse_transform(y_test)).rename(columns={0:"status"})
y_status.head()

status
0       0
1       0
2       0
3       0
4       0

In [150]:
from sklearn.metrics import f1_score
scores=[f1_score(y_status, to_labels(y_probs1,t)) for t in thresholds]

In [151]:
ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.539, 0.8799999999999999)


In [207]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.57),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.57),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.57),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.57),0,y_pred.pred_1)

In [211]:
#y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_1)

In [212]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  21


In [213]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  27


In [214]:
y_true=y_test.rename(columns={0:"y_0",1:"y_1"})

In [215]:
compare=pd.concat([y_true,y_pred],axis=1)
pd.DataFrame(np.where(compare["pred_0"]==compare["y_0"])).shape

(1, 41)

In [216]:
len(y_true[y_true["y_1"]==1])

24

In [217]:
print("Accuracy after adjusting threshold: ",41/48)

Accuracy after adjusting threshold:  0.8541666666666666


In [218]:
print("Confusion matrix: \n",np.asarray([[19,5],[2,22]]))

Confusion matrix: 
 [[19  5]
 [ 2 22]]


In [219]:
print("Sensitivity: ",22/24)
print("Specificity: ",19/24)

Sensitivity:  0.9166666666666666
Specificity:  0.7916666666666666


In [220]:
print("Estimated AUC: ",(22/24+19/24)/2)

Estimated AUC:  0.8541666666666666
