In [1]:
import pandas as pd
df=pd.read_csv("seeds_dataset.csv")
df.head()

Area  Perimeter  Compactness  Kernel_L  Kernel_W  Asymmetry_coef  \
0  15.26      14.84       0.8710     5.763     3.312           2.221   
1  14.88      14.57       0.8811     5.554     3.333           1.018   
2  14.29      14.09       0.9050     5.291     3.337           2.699   
3  13.84      13.94       0.8955     5.324     3.379           2.259   
4  16.14      14.99       0.9034     5.658     3.562           1.355   

   Kernel_GL  Varieties  
0      5.220          1  
1      4.956          1  
2      4.825          1  
3      4.805          1  
4      5.175          1

In [2]:
X=df.drop(["Varieties"],axis=1)
X.head()

Area  Perimeter  Compactness  Kernel_L  Kernel_W  Asymmetry_coef  \
0  15.26      14.84       0.8710     5.763     3.312           2.221   
1  14.88      14.57       0.8811     5.554     3.333           1.018   
2  14.29      14.09       0.9050     5.291     3.337           2.699   
3  13.84      13.94       0.8955     5.324     3.379           2.259   
4  16.14      14.99       0.9034     5.658     3.562           1.355   

   Kernel_GL  
0      5.220  
1      4.956  
2      4.825  
3      4.805  
4      5.175

In [3]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
X=pd.DataFrame(est.fit_transform(X),columns=X.columns)
X.head()

Area  Perimeter  Compactness  Kernel_L  Kernel_W  Asymmetry_coef  Kernel_GL
0   1.0        2.0          2.0       1.0       1.0             0.0        1.0
1   1.0        1.0          2.0       1.0       2.0             0.0        0.0
2   1.0        1.0          3.0       0.0       2.0             1.0        0.0
3   1.0        1.0          3.0       0.0       2.0             0.0        0.0
4   2.0        2.0          3.0       1.0       2.0             0.0        1.0

In [4]:
y=df[["Varieties"]]
y.groupby("Varieties")["Varieties"].count()

Varieties
1    70
2    70
3    70
Name: Varieties, dtype: int64

In [5]:
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
import numpy as np

In [6]:
LR=LogisticRegression(C=3,solver="lbfgs",random_state=0)
scores=cross_val_score(LR,X,np.asarray(y).reshape(y.shape[0],),cv=10)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

Accuracy:  0.9523809523809523 +/- 0.05216405309573012


In [7]:
y_pred = cross_val_predict(LR, X,np.asarray(y).reshape(y.shape[0],), cv=10)

In [8]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[66  1  3]
 [ 3 67  0]
 [ 3  0 67]]


In [9]:
from sklearn.metrics import classification_report
print("Classification report: \n",classification_report(y,y_pred))

Classification report: 
               precision    recall  f1-score   support

           1       0.92      0.94      0.93        70
           2       0.99      0.96      0.97        70
           3       0.96      0.96      0.96        70

    accuracy                           0.95       210
   macro avg       0.95      0.95      0.95       210
weighted avg       0.95      0.95      0.95       210

