In [1]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_5aa6bf17984840e9901062d8dce3c4cd.csv"
df=pd.read_csv(url)
df.head()

behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0                   10               13                       12   
1                   10               11                       11   
2                   10               15                        3   
3                   10               11                       10   
4                    8               11                        7   

   intention_aggregation  intention_commitment  attitude_consistency  \
0                      4                     7                     9   
1                     10                    14                     7   
2                      2                    14                     8   
3                     10                    15                     7   
4                      8                    10                     7   

   attitude_spontaneity  norm_significantPerson  norm_fulfillment  \
0                    10                       1                 8   
1                     7                       5                 5   
2                    10                       1                 4   
3                     7                       1                 5   
4                     8                       1                 5   

   perception_vulnerability  perception_severity  motivation_strength  \
0                         7                    3                   14   
1                         4                    2                   15   
2                         7                    2                    7   
3                         4                    2                   15   
4                         3                    2                   15   

   motivation_willingness  socialSupport_emotionality  \
0                       8                           5   
1                      13                           7   
2                       3                           3   
3                      13                           7   
4                       5                           3   

   socialSupport_appreciation  socialSupport_instrumental  \
0                           7                          12   
1                           6                           5   
2                           6                          11   
3                           4                           4   
4                           6                          12   

   empowerment_knowledge  empowerment_abilities  empowerment_desires  \
0                     12                     11                    8   
1                      5                      4                    4   
2                      3                      3                   15   
3                      4                      4                    4   
4                      5                      4                    7   

   ca_cervix  
0          1  
1          1  
2          1  
3          1  
4          1

In [2]:
df.shape

(72, 20)

In [3]:
X=df.drop(["ca_cervix"],axis=1)
X.head()

behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0                   10               13                       12   
1                   10               11                       11   
2                   10               15                        3   
3                   10               11                       10   
4                    8               11                        7   

   intention_aggregation  intention_commitment  attitude_consistency  \
0                      4                     7                     9   
1                     10                    14                     7   
2                      2                    14                     8   
3                     10                    15                     7   
4                      8                    10                     7   

   attitude_spontaneity  norm_significantPerson  norm_fulfillment  \
0                    10                       1                 8   
1                     7                       5                 5   
2                    10                       1                 4   
3                     7                       1                 5   
4                     8                       1                 5   

   perception_vulnerability  perception_severity  motivation_strength  \
0                         7                    3                   14   
1                         4                    2                   15   
2                         7                    2                    7   
3                         4                    2                   15   
4                         3                    2                   15   

   motivation_willingness  socialSupport_emotionality  \
0                       8                           5   
1                      13                           7   
2                       3                           3   
3                      13                           7   
4                       5                           3   

   socialSupport_appreciation  socialSupport_instrumental  \
0                           7                          12   
1                           6                           5   
2                           6                          11   
3                           4                           4   
4                           6                          12   

   empowerment_knowledge  empowerment_abilities  empowerment_desires  
0                     12                     11                    8  
1                      5                      4                    4  
2                      3                      3                   15  
3                      4                      4                    4  
4                      5                      4                    7

In [4]:
y=df[["ca_cervix"]]
y.value_counts()

ca_cervix
0            51
1            21
dtype: int64

In [5]:
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import LeaveOneOut
from sklearn import metrics
from sklearn.metrics import auc
from sklearn.metrics import plot_roc_curve
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold

In [6]:
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

test = SelectKBest(score_func=f_classif, k="all")
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

scores
17  29.171896
10  24.375813
16  21.163032
11  19.558959
18  18.664926
12  15.787657
8   15.669342
9   15.264080
13  12.702173
2   11.294690
14   7.619211
0    7.502791
7    6.614904
3    6.511008
4    4.167306
1    2.927568
15   1.290717
5    1.119208
6    0.504491

In [7]:
X_scores=scores[scores["scores"]>12]
len(X_scores)

9

In [8]:
Xp=X.iloc[:,X_scores.index]
Xp.head()

empowerment_abilities  perception_severity  empowerment_knowledge  \
0                     11                    3                     12   
1                      4                    2                      5   
2                      3                    2                      3   
3                      4                    2                      4   
4                      4                    2                      5   

   motivation_strength  empowerment_desires  motivation_willingness  \
0                   14                    8                       8   
1                   15                    4                      13   
2                    7                   15                       3   
3                   15                    4                      13   
4                   15                    7                       5   

   norm_fulfillment  perception_vulnerability  socialSupport_emotionality  
0                 8                         7                           5  
1                 5                         4                           7  
2                 4                         7                           3  
3                 5                         4                           7  
4                 5                         3                           3

In [9]:
from sklearn import svm
model1=svm.SVC(random_state=0)
scores=cross_val_score(model1,Xp,np.asarray(y).reshape(y.shape[0],),cv=5)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

Accuracy:  0.9323809523809524 +/- 0.059658894336631706


In [10]:
y_pred = cross_val_predict(model1, Xp, np.asarray(y).reshape(y.shape[0],), cv=5)
print("AUC: ",roc_auc_score(y,y_pred))

AUC:  0.9089635854341738


In [11]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[49  2]
 [ 3 18]]


In [12]:
print("True positive rate: ",18/21)
print("True negative rate: ",49/51)

True positive rate:  0.8571428571428571
True negative rate:  0.9607843137254902


In [13]:
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

scores
17  29.171896
10  24.375813
16  21.163032
11  19.558959
18  18.664926
12  15.787657
8   15.669342
9   15.264080
13  12.702173
2   11.294690
14   7.619211
0    7.502791
7    6.614904
3    6.511008
4    4.167306
1    2.927568
15   1.290717
5    1.119208
6    0.504491

In [14]:
X_scores=scores[scores["scores"]>2]
len(X_scores)

16

In [15]:
Xp=X.iloc[:,X_scores.index]

In [16]:
from sklearn.naive_bayes import GaussianNB
model2=GaussianNB()
scores=cross_val_score(model2,Xp,np.asarray(y).reshape(y.shape[0],),cv=8)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

Accuracy:  0.9305555555555556 +/- 0.053791435363991925


In [17]:
y_pred = cross_val_predict(model2, Xp, np.asarray(y).reshape(y.shape[0],), cv=8)
print("AUC: ",roc_auc_score(y,y_pred))

AUC:  0.92296918767507


In [18]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[48  3]
 [ 2 19]]


In [56]:
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

scores
17  29.171896
10  24.375813
16  21.163032
11  19.558959
18  18.664926
12  15.787657
8   15.669342
9   15.264080
13  12.702173
2   11.294690
14   7.619211
0    7.502791
7    6.614904
3    6.511008
4    4.167306
1    2.927568
15   1.290717
5    1.119208
6    0.504491

In [57]:
X_scores=scores[scores["scores"]>1]
len(X_scores)

18

In [58]:
Xp=X.iloc[:,X_scores.index]

In [67]:
from sklearn.linear_model import LogisticRegression
model3=LogisticRegression(class_weight="balanced",max_iter=300,random_state=0)
scores=cross_val_score(model3,Xp,np.asarray(y).reshape(y.shape[0],),cv=9)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

Accuracy:  0.9583333333333334 +/- 0.11785113019775792


In [68]:
scores

array([1.   , 1.   , 0.625, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ])

In [69]:
y_pred = cross_val_predict(model3, Xp, np.asarray(y).reshape(y.shape[0],), cv=9)
print("AUC: ",roc_auc_score(y,y_pred))

AUC:  0.9425770308123248


In [70]:
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

Confusion matrix: 
 [[50  1]
 [ 2 19]]


In [71]:
fpr, tpr, thresholds = metrics.roc_curve(y,y_pred,pos_label=1)

In [72]:
print("True negative rate: ",(1-pd.DataFrame(fpr).loc[1]).values)

True negative rate:  [0.98]


In [73]:
print("True positive rate: ",(pd.DataFrame(tpr).loc[1]).values)

True positive rate:  [0.905]
